const fs = require('fs');
const path = require('path');
const ExcelJS = require('exceljs');

// Database of 100 new qualified prospects (completely different from V1)
const prospects = [
  // 1-20: AI, DeepTech & SaaS (New)
  {
    name: "Apeksha Jain",
    title: "Senior HR Manager",
    company: "Yellow.ai",
    website: "https://yellow.ai",
    linkedin: "https://www.linkedin.com/in/apeksha-jain-yellowai",
    companyLinkedin: "https://www.linkedin.com/company/yellowdotai",
    email: "apeksha.jain@yellow.ai",
    pattern: "first.last@yellow.ai",
    size: "501-1000",
    industry: "Conversational AI SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student developers trained in NLP, chat-bot integration, and Python script deployment.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://yellow.ai/careers"
  },
  {
    name: "Rohan Vasudevan",
    title: "Head of Talent Acquisition",
    company: "Sarvam AI",
    website: "https://www.sarvam.ai",
    linkedin: "https://www.linkedin.com/in/rohan-vasudevan-sarvam",
    companyLinkedin: "https://www.linkedin.com/company/sarvam-ai",
    email: "rohan@sarvam.ai",
    pattern: "first@sarvam.ai",
    size: "11-50",
    industry: "Generative AI Research",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can connect Sarvam AI with student research assistants to help curate Indic language datasets.",
    hiringInterns: "Yes",
    campusHiring: "No",
    source: "https://www.sarvam.ai"
  },
  {
    name: "Karan Shah",
    title: "HR Director",
    company: "Haptik",
    website: "https://www.haptik.ai",
    linkedin: "https://www.linkedin.com/in/karan-shah-haptik",
    companyLinkedin: "https://www.linkedin.com/company/haptik",
    email: "karan.shah@haptik.ai",
    pattern: "first.last@haptik.ai",
    size: "201-500",
    industry: "Enterprise AI SaaS",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide student QA testers and UI/UX design ambassadors for conversational flows.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.haptik.ai/careers"
  },
  {
    name: "Priyesh Kumar",
    title: "VP Human Resources",
    company: "Gupshup",
    website: "https://www.gupshup.io",
    linkedin: "https://www.linkedin.com/in/priyeshkumar-gupshup",
    companyLinkedin: "https://www.linkedin.com/company/gupshup",
    email: "priyesh.kumar@gupshup.io",
    pattern: "first.last@gupshup.io",
    size: "1001-5000",
    industry: "Conversational Messaging SaaS",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply business development and client-onboarding student ambassadors.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.gupshup.io/careers"
  },
  {
    name: "Nisha Rao",
    title: "Talent Partner",
    company: "Wadhwani AI",
    website: "https://www.wadhwaniai.org",
    linkedin: "https://www.linkedin.com/in/nisharao-wadhwani",
    companyLinkedin: "https://www.linkedin.com/company/wadhwaniai",
    email: "nisha@wadhwaniai.org",
    pattern: "first@wadhwaniai.org",
    size: "51-200",
    industry: "AI for Social Good",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can connect Wadhwani AI with student data enumerators and field validation helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.wadhwaniai.org/careers"
  },
  {
    name: "Divya Teja",
    title: "HR Business Partner",
    company: "CoRover",
    website: "https://corover.ai",
    linkedin: "https://www.linkedin.com/in/divyateja-corover",
    companyLinkedin: "https://www.linkedin.com/company/corover",
    email: "divya@corover.mobi",
    pattern: "first@corover.mobi",
    size: "51-200",
    industry: "Conversational AI / BharatGPT",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply Indic language content curators and chatbot testers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://corover.ai"
  },
  {
    name: "Tanvi Srivastav",
    title: "Head HR",
    company: "Karya",
    website: "https://www.karya.in",
    linkedin: "https://www.linkedin.com/in/tanvi-srivastav-karya",
    companyLinkedin: "https://www.linkedin.com/company/karya-inc",
    email: "tanvi@karya.in",
    pattern: "first@karya.in",
    size: "11-50",
    industry: "Ethical Data / AI",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can mobilize thousands of rural & semi-urban students for local speech/text data collection tasks.",
    hiringInterns: "Yes",
    campusHiring: "No",
    source: "https://www.karya.in"
  },
  {
    name: "Anjali Deshmukh",
    title: "HR Lead",
    company: "Krutrim AI",
    website: "https://olakrutrim.com",
    linkedin: "https://www.linkedin.com/in/anjali-deshmukh-krutrim",
    companyLinkedin: "https://www.linkedin.com/company/krutrim-si-designs",
    email: "anjali.d@olakrutrim.com",
    pattern: "first.last@olakrutrim.com",
    size: "101-250",
    industry: "AI Silicon & LLMs",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply computer science student ambassadors to support developer outreach and APIs.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://olakrutrim.com"
  },
  {
    name: "Amit Malhotra",
    title: "VP HR",
    company: "Fractal Analytics",
    website: "https://fractal.ai",
    linkedin: "https://www.linkedin.com/in/amitmalhotra-fractal",
    companyLinkedin: "https://www.linkedin.com/company/fractal-analytics",
    email: "amit.malhotra@fractal.ai",
    pattern: "first.last@fractal.ai",
    size: "5000+",
    industry: "AI & Decision Sciences",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can run campus hackathons to source top final-year statistics and data science students.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://fractal.ai/careers"
  },
  {
    name: "Sonia Joseph",
    title: "Director TA",
    company: "Mu Sigma",
    website: "https://www.mu-sigma.com",
    linkedin: "https://www.linkedin.com/in/soniajoseph-musigma",
    companyLinkedin: "https://www.linkedin.com/company/mu-sigma",
    email: "sonia.joseph@mu-sigma.com",
    pattern: "first.last@mu-sigma.com",
    size: "1001-5000",
    industry: "Decision Sciences & Analytics",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can help with campus brand building to attract analytical students for decision sciences roles.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.mu-sigma.com/careers"
  },
  {
    name: "Preeti Sinha",
    title: "Talent Lead",
    company: "Druva",
    website: "https://www.druva.com",
    linkedin: "https://www.linkedin.com/in/preetisinha-druva",
    companyLinkedin: "https://www.linkedin.com/company/druva",
    email: "preeti.sinha@druva.com",
    pattern: "first.last@druva.com",
    size: "501-1000",
    industry: "Cloud Data Protection",
    location: "Pune, India",
    pitch: "NextGenGrowth can supply cybersecurity-trained students for customer-success and technical support tasks.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.druva.com/careers"
  },
  {
    name: "Suresh Pillai",
    title: "Director Talent Acquisition",
    company: "BrowserStack",
    website: "https://www.browserstack.com",
    linkedin: "https://www.linkedin.com/in/sureshpillai-browserstack",
    companyLinkedin: "https://www.linkedin.com/company/browserstack",
    email: "suresh@browserstack.com",
    pattern: "first@browserstack.com",
    size: "501-1000",
    industry: "Mobile App Testing SaaS",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide student developers for API integrations and documentation testing.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.browserstack.com/careers"
  },
  {
    name: "Niranjan K",
    title: "Head HR",
    company: "Darwinbox",
    website: "https://darwinbox.com",
    linkedin: "https://www.linkedin.com/in/niranjank-darwinbox",
    companyLinkedin: "https://www.linkedin.com/company/darwinbox",
    email: "niranjan.k@darwinbox.co",
    pattern: "first.last@darwinbox.co",
    size: "501-1000",
    industry: "HR Tech SaaS",
    location: "Hyderabad, India",
    pitch: "NextGenGrowth can supply student sales development representatives to source corporate client leads.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://darwinbox.com/careers"
  },
  {
    name: "Sruthi Gowda",
    title: "Senior Talent Partner",
    company: "Whatfix",
    website: "https://whatfix.com",
    linkedin: "https://www.linkedin.com/in/sruthigowda-whatfix",
    companyLinkedin: "https://www.linkedin.com/company/whatfix",
    email: "sruthi.gowda@whatfix.com",
    pattern: "first.last@whatfix.com",
    size: "501-1000",
    industry: "Digital Adoption Platform",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student content creators to draft platform walkthroughs and tutorials.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://whatfix.com/careers"
  },
  {
    name: "Rajesh Nair",
    title: "VP HR",
    company: "CleverTap",
    website: "https://clevertap.com",
    linkedin: "https://www.linkedin.com/in/rajeshnair-clevertap",
    companyLinkedin: "https://www.linkedin.com/company/clevertap",
    email: "rajesh.nair@clevertap.com",
    pattern: "first.last@clevertap.com",
    size: "501-1000",
    industry: "Customer Retention SaaS",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can feed junior marketing analysts to track user engagement campaigns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://clevertap.com/careers"
  },
  {
    name: "Archana Kamath",
    title: "Global Recruiting Lead",
    company: "Leadsquared",
    website: "https://www.leadsquared.com",
    linkedin: "https://www.linkedin.com/in/archanakamath-leadsquared",
    companyLinkedin: "https://www.linkedin.com/company/leadsquared",
    email: "archana.kamath@leadsquared.com",
    pattern: "first.last@leadsquared.com",
    size: "501-1000",
    industry: "Sales Execution CRM",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student sales and lead generation interns in tier-2 cities.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.leadsquared.com/careers"
  },
  {
    name: "Tarun G",
    title: "Director TA",
    company: "HighRadius",
    website: "https://www.highradius.com",
    linkedin: "https://www.linkedin.com/in/tarung-highradius",
    companyLinkedin: "https://www.linkedin.com/company/highradius",
    email: "tarun.g@highradius.com",
    pattern: "first.last@highradius.com",
    size: "1001-5000",
    industry: "Fintech SaaS / Treasury AI",
    location: "Bhubaneswar, India",
    pitch: "NextGenGrowth can run campus ambassador programs in technical colleges across Eastern India.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.highradius.com/careers"
  },
  {
    name: "Neetu Sharma",
    title: "HR Head",
    company: "Zenoti",
    website: "https://www.zenoti.com",
    linkedin: "https://www.linkedin.com/in/neetusharma-zenoti",
    companyLinkedin: "https://www.linkedin.com/company/zenoti",
    email: "neetu.sharma@zenoti.com",
    pattern: "first.last@zenoti.com",
    size: "501-1000",
    industry: "Salon & Spa Software SaaS",
    location: "Hyderabad, India",
    pitch: "NextGenGrowth can provide junior frontend developers and support coordinators.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.zenoti.com/careers"
  },
  {
    name: "Manoj Kumar",
    title: "Lead Talent Partner",
    company: "WebEngage",
    website: "https://webengage.com",
    linkedin: "https://www.linkedin.com/in/manojkumar-webengage",
    companyLinkedin: "https://www.linkedin.com/company/webengage",
    email: "manoj@webengage.com",
    pattern: "first@webengage.com",
    size: "201-500",
    industry: "User Engagement SaaS",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student community moderators and campaign coordinators.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://webengage.com/careers"
  },
  {
    name: "Shweta Mehta",
    title: "Head People Success",
    company: "Hevo Data",
    website: "https://hevodata.com",
    linkedin: "https://www.linkedin.com/in/shwetamehta-hevo",
    companyLinkedin: "https://www.linkedin.com/company/hevodata",
    email: "shweta@hevodata.com",
    pattern: "first@hevodata.com",
    size: "101-250",
    industry: "Data Integration SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can feed database and SQL-trained student QA engineers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://hevodata.com/careers"
  },

  // 21-40: LogiTech & Mobility (New)
  {
    name: "Pooja Gupta",
    title: "VP HR",
    company: "Delhivery",
    website: "https://www.delhivery.com",
    linkedin: "https://www.linkedin.com/in/poojagupta-delhivery",
    companyLinkedin: "https://www.linkedin.com/company/delhivery",
    email: "pooja.gupta@delhivery.com",
    pattern: "first.last@delhivery.com",
    size: "5000+",
    industry: "Logistics & Supply Chain",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply regional logistics operations and route auditor student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.delhivery.com/careers"
  },
  {
    name: "Komal Bhatia",
    title: "HR Director",
    company: "Shiprocket",
    website: "https://www.shiprocket.in",
    linkedin: "https://www.linkedin.com/in/komalbhatia-shiprocket",
    companyLinkedin: "https://www.linkedin.com/company/shiprocket",
    email: "komal.bhatia@shiprocket.com",
    pattern: "first.last@shiprocket.com",
    size: "1001-5000",
    industry: "E-commerce Logistics",
    location: "Delhi, India",
    pitch: "NextGenGrowth can supply campus student ambassadors to onboard local social commerce sellers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.shiprocket.in/careers"
  },
  {
    name: "Sachin Sharma",
    title: "Head of Talent Acquisition",
    company: "Porter",
    website: "https://porter.in",
    linkedin: "https://www.linkedin.com/in/sachinsharma-porter",
    companyLinkedin: "https://www.linkedin.com/company/porter.in",
    email: "sachin@porter.in",
    pattern: "first@porter.in",
    size: "1001-5000",
    industry: "Intracity Logistics",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can recruit student auditors to conduct local driver partner verification audits.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://porter.in/careers"
  },
  {
    name: "Arindam Lahiri",
    title: "Chief Human Resources Officer",
    company: "Shadowfax",
    website: "https://www.shadowfax.in",
    linkedin: "https://www.linkedin.com/in/arindam-lahiri-shadowfax",
    companyLinkedin: "https://www.linkedin.com/company/shadowfax",
    email: "arindam.lahiri@shadowfax.in",
    pattern: "first.last@shadowfax.in",
    size: "1001-5000",
    industry: "On-demand Logistics",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can source operational coordinators to manage delivery fleets in tier-3 university hubs.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.shadowfax.in/careers"
  },
  {
    name: "Swati Rathi",
    title: "Head HR",
    company: "Xpressbees",
    website: "https://www.xpressbees.com",
    linkedin: "https://www.linkedin.com/in/swatirathi-xpressbees",
    companyLinkedin: "https://www.linkedin.com/company/xpressbees",
    email: "swati.rathi@xpressbees.com",
    pattern: "first.last@xpressbees.com",
    size: "5000+",
    industry: "E-commerce Logistics / Express",
    location: "Pune, India",
    pitch: "NextGenGrowth can provide student coordinators to run seasonal campus parcel delivery hubs.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.xpressbees.com/careers"
  },
  {
    name: "Nikhil Joshi",
    title: "Lead TA",
    company: "ElasticRun",
    website: "https://www.elasticrun.com",
    linkedin: "https://www.linkedin.com/in/nikhiljoshi-elasticrun",
    companyLinkedin: "https://www.linkedin.com/company/elasticrun",
    email: "nikhil.joshi@elasticrun.com",
    pattern: "first.last@elasticrun.com",
    size: "1001-5000",
    industry: "Rural Commerce Logistics",
    location: "Pune, India",
    pitch: "NextGenGrowth can provide rural-hailing student partners for retail merchant verification.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://elasticrun.com"
  },
  {
    name: "Meenakshi K",
    title: "HR Director",
    company: "Ninjacart",
    website: "https://www.ninjacart.in",
    linkedin: "https://www.linkedin.com/in/meenakshik-ninjacart",
    companyLinkedin: "https://www.linkedin.com/company/ninjacart",
    email: "meenakshi@ninjacart.co",
    pattern: "first@ninjacart.co",
    size: "1001-5000",
    industry: "Agritech Logistics",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply supply-chain management student interns for local distribution center audits.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.ninjacart.in/careers"
  },
  {
    name: "Vinod Kumar",
    title: "VP HR",
    company: "WayCool Foods",
    website: "https://www.waycool.in",
    linkedin: "https://www.linkedin.com/in/vinodkumar-waycool",
    companyLinkedin: "https://www.linkedin.com/company/waycool-foods-&-products-pvt-ltd",
    email: "vinod@waycool.in",
    pattern: "first@waycool.in",
    size: "1001-5000",
    industry: "Food Supply Chain Logistics",
    location: "Chennai, India",
    pitch: "NextGenGrowth can supply food-tech and logistics student ambassadors in Southern India.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.waycool.in"
  },
  {
    name: "Aditi Roy",
    title: "Head Talent Acquisition",
    company: "Rapido",
    website: "https://www.rapido.bike",
    linkedin: "https://www.linkedin.com/in/aditiroy-rapido",
    companyLinkedin: "https://www.linkedin.com/company/rapido-bike",
    email: "aditi.roy@rapido.bike",
    pattern: "first.last@rapido.bike",
    size: "1001-5000",
    industry: "Bike Taxi & Logistic",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can recruit student campus representatives to launch on-campus driver sign-up runs.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://rapido.bike"
  },
  {
    name: "Shruti Goel",
    title: "HR Head",
    company: "Bounce",
    website: "https://bounceShare.com",
    linkedin: "https://www.linkedin.com/in/shrutigoel-bounce",
    companyLinkedin: "https://www.linkedin.com/company/bounceshare",
    email: "shruti.goel@bounceshare.com",
    pattern: "first.last@bounceshare.com",
    size: "201-500",
    industry: "Electric Mobility",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply campus micro-mobility promotion teams and student marketing reps.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://bounceShare.com"
  },
  {
    name: "Preetham S",
    title: "VP HR",
    company: "Ola Electric",
    website: "https://www.olaelectric.com",
    linkedin: "https://www.linkedin.com/in/preethams-ola",
    companyLinkedin: "https://www.linkedin.com/company/olaelectric",
    email: "preetham.s@olaelectric.com",
    pattern: "first.last@olaelectric.com",
    size: "1001-5000",
    industry: "EV Mobility",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can launch EV awareness drives and student test-drive programs in college campuses.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.olaelectric.com"
  },
  {
    name: "Vikram Sen",
    title: "Head HR",
    company: "Ather Energy",
    website: "https://www.atherenergy.com",
    linkedin: "https://www.linkedin.com/in/vikramsen-ather",
    companyLinkedin: "https://www.linkedin.com/company/ather-energy",
    email: "vikram@atherenergy.com",
    pattern: "first@atherenergy.com",
    size: "1001-5000",
    industry: "EV Manufacturing & Tech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student community builders to run Ather owner fan-clubs in university circles.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.atherenergy.com/careers"
  },
  {
    name: "Komal Saxena",
    title: "HR Director",
    company: "BluSmart",
    website: "https://blu-smart.com",
    linkedin: "https://www.linkedin.com/in/komalsaxena-blusmart",
    companyLinkedin: "https://www.linkedin.com/company/blusmart-mobility",
    email: "komal.saxena@blu-smart.com",
    pattern: "first.last@blu-smart.com",
    size: "1001-5000",
    industry: "Electric Ride Hailing",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide green-energy student campus leads to build localized launch awareness.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://blu-smart.com"
  },
  {
    name: "Naveen Raj",
    title: "HR Head",
    company: "Shuttl",
    website: "https://shuttl.com",
    linkedin: "https://www.linkedin.com/in/naveenraj-shuttl",
    companyLinkedin: "https://www.linkedin.com/company/shuttl",
    email: "naveen@shuttl.com",
    pattern: "first@shuttl.com",
    size: "201-500",
    industry: "Bus Mobility Tech",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can deploy on-campus student representatives to manage shuttle schedule surveys.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://shuttl.com"
  },
  {
    name: "Rohit Verma",
    title: "Lead Recruiter",
    company: "LocoNav India",
    website: "https://loconav.com",
    linkedin: "https://www.linkedin.com/in/rohitverma-loconav",
    companyLinkedin: "https://www.linkedin.com/company/loconav",
    email: "rohit.verma@loconav.com",
    pattern: "first.last@loconav.com",
    size: "201-500",
    industry: "Fleet Telematics Software",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide telemetry validation and student software QA interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://loconav.com/careers"
  },
  {
    name: "Sonam Choki",
    title: "Talent Specialist",
    company: "Blowhorn",
    website: "https://blowhorn.com",
    linkedin: "https://www.linkedin.com/in/sonam-blowhorn",
    companyLinkedin: "https://www.linkedin.com/company/blowhorn",
    email: "sonam@blowhorn.com",
    pattern: "first@blowhorn.com",
    size: "201-500",
    industry: "Intracity Logistics Tech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply operations monitoring and regional customer support student talent.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://blowhorn.com"
  },
  {
    name: "Harish Murthy",
    title: "HR Director",
    company: "Chalo",
    website: "https://chalo.com",
    linkedin: "https://www.linkedin.com/in/harishmurthy-chalo",
    companyLinkedin: "https://www.linkedin.com/company/chalo-bus-tracker",
    email: "harish@chalo.com",
    pattern: "first@chalo.com",
    size: "501-1000",
    industry: "Public Transport App",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student surveyors to collect localized city bus route feedback.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://chalo.com"
  },
  {
    name: "Shyam Sundar",
    title: "Senior TA Specialist",
    company: "Shadowfax Logistics",
    website: "https://www.shadowfax.in",
    linkedin: "https://www.linkedin.com/in/shyamsundar-sf",
    companyLinkedin: "https://www.linkedin.com/company/shadowfax",
    email: "shyam.sundar@shadowfax.in",
    pattern: "first.last@shadowfax.in",
    size: "1001-5000",
    industry: "Last-mile Delivery Logistics",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide regional logistics management and student coordinator interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.shadowfax.in/careers"
  },
  {
    name: "Trupti G",
    title: "Talent Acquisition Head",
    company: "Delhivery Express",
    website: "https://www.delhivery.com",
    linkedin: "https://www.linkedin.com/in/truptig-delhivery",
    companyLinkedin: "https://www.linkedin.com/company/delhivery",
    email: "trupti.g@delhivery.com",
    pattern: "first.last@delhivery.com",
    size: "5000+",
    industry: "B2B Logistics",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can feed data processing and operations management student talent.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.delhivery.com/careers"
  },
  {
    name: "Anusha V",
    title: "Talent Lead",
    company: "Porter Delivery",
    website: "https://porter.in",
    linkedin: "https://www.linkedin.com/in/anushav-porter",
    companyLinkedin: "https://www.linkedin.com/company/porter.in",
    email: "anusha.v@porter.in",
    pattern: "first.last@porter.in",
    size: "1001-5000",
    industry: "Mini Truck Mobility",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply operations research and regional audit student helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://porter.in/careers"
  },

  // 41-60: HealthTech, Biotech & Wellness (New)
  {
    name: "Anupama Nair",
    title: "Head Human Resources",
    company: "PharmEasy",
    website: "https://pharmeasy.in",
    linkedin: "https://www.linkedin.com/in/anupamanair-pharmeasy",
    companyLinkedin: "https://www.linkedin.com/company/pharmeasy",
    email: "anupama.nair@pharmeasy.in",
    pattern: "first.last@pharmeasy.in",
    size: "1001-5000",
    industry: "E-Pharmacy & Diagnostics",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide student pharmacy leads to promote digital health packages to college families.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://pharmeasy.in/careers"
  },
  {
    name: "Shreya Sharma",
    title: "Lead TA Manager",
    company: "Tata 1mg",
    website: "https://www.1mg.com",
    linkedin: "https://www.linkedin.com/in/shreyasharma-1mg",
    companyLinkedin: "https://www.linkedin.com/company/1mg",
    email: "shreya.sharma@1mg.com",
    pattern: "first.last@1mg.com",
    size: "1001-5000",
    industry: "E-Healthcare SaaS",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply student marketing reps to raise local awareness for lab testing campaigns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.1mg.com/careers"
  },
  {
    name: "Karan Johar",
    title: "HR Director",
    company: "HealthifyMe",
    website: "https://www.healthifyme.com",
    linkedin: "https://www.linkedin.com/in/karanjohar-healthifyme",
    companyLinkedin: "https://www.linkedin.com/company/healthifyme",
    email: "karan@healthifyme.com",
    pattern: "first@healthifyme.com",
    size: "501-1000",
    industry: "Fitness & Wellness Tech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can source student wellness ambassadors to promote fitness challenges inside campuses.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.healthifyme.com"
  },
  {
    name: "Ria Sengupta",
    title: "Head of Talent Acquisition",
    company: "Pristyn Care",
    website: "https://www.pristyncare.com",
    linkedin: "https://www.linkedin.com/in/riasengupta-pristyncare",
    companyLinkedin: "https://www.linkedin.com/company/pristyn-care",
    email: "ria.sengupta@pristyncare.com",
    pattern: "first.last@pristyncare.com",
    size: "1001-5000",
    industry: "Surgical Healthcare Care",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply healthcare coordinator interns to assist patient care managers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.pristyncare.com/careers"
  },
  {
    name: "Rahul Sinha",
    title: "CHRO",
    company: "Cure.fit",
    website: "https://www.cult.fit",
    linkedin: "https://www.linkedin.com/in/rahulsinha-cultfit",
    companyLinkedin: "https://www.linkedin.com/company/cult-fit",
    email: "rahul.sinha@cult.fit",
    pattern: "first.last@cult.fit",
    size: "1001-5000",
    industry: "Fitness & Cult Gyms",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can deploy student fit-ambassadors to drive Cult.fit pass signups on campuses.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.cult.fit"
  },
  {
    name: "Gaurav Malhotra",
    title: "HR Manager",
    company: "MediBuddy",
    website: "https://www.medibuddy.in",
    linkedin: "https://www.linkedin.com/in/gaurav-medibuddy",
    companyLinkedin: "https://www.linkedin.com/company/medibuddy",
    email: "gaurav.m@medibuddy.in",
    pattern: "first.last@medibuddy.in",
    size: "501-1000",
    industry: "Digital Consultations Tech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student telehealth coordinators to run virtual consult camps.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.medibuddy.in"
  },
  {
    name: "Preeti Nair",
    title: "HR Head",
    company: "Practo",
    website: "https://www.practo.com",
    linkedin: "https://www.linkedin.com/in/preetinaifr-practo",
    companyLinkedin: "https://www.linkedin.com/company/practo-technologies",
    email: "preeti.n@practo.com",
    pattern: "first.last@practo.com",
    size: "1001-5000",
    industry: "Doctor Discovery Software",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student clinic auditor interns in metro locations.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.practo.com/careers"
  },
  {
    name: "Vikrant Patil",
    title: "VP HR Success",
    company: "Innovaccer",
    website: "https://innovaccer.com",
    linkedin: "https://www.linkedin.com/in/vikrant-patil-innovaccer",
    companyLinkedin: "https://www.linkedin.com/company/innovaccer",
    email: "vikrant.patil@innovaccer.com",
    pattern: "first.last@innovaccer.com",
    size: "1001-5000",
    industry: "Healthcare Cloud SaaS",
    location: "Noida, India",
    pitch: "NextGenGrowth can supply bio-informatics and computer science student QA engineers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://innovaccer.com/careers"
  },
  {
    name: "Nisha Patel",
    title: "Talent Specialist",
    company: "Portea Medical",
    website: "https://www.portea.com",
    linkedin: "https://www.linkedin.com/in/nishapatel-portea",
    companyLinkedin: "https://www.linkedin.com/company/portea-medical",
    email: "nisha.patel@portea.com",
    pattern: "first.last@portea.com",
    size: "1001-5000",
    industry: "Home Healthcare Services",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can source student support team interns and home-care operational leads.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.portea.com"
  },
  {
    name: "Sweta Singh",
    title: "Lead Talent Partner",
    company: "Healthkart",
    website: "https://www.healthkart.com",
    linkedin: "https://www.linkedin.com/in/swetasingh-healthkart",
    companyLinkedin: "https://www.linkedin.com/company/healthkart",
    email: "sweta.singh@healthkart.com",
    pattern: "first.last@healthkart.com",
    size: "501-1000",
    industry: "Nutritional Supplements",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can mobilize student sports and wellness ambassadors to test new products.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.healthkart.com/careers"
  },
  {
    name: "Ranjit Roy",
    title: "HR Director",
    company: "PhableCare",
    website: "https://phablecare.com",
    linkedin: "https://www.linkedin.com/in/ranjitroy-phable",
    companyLinkedin: "https://www.linkedin.com/company/phable",
    email: "ranjit@phable.com",
    pattern: "first@phable.com",
    size: "201-500",
    industry: "Chronic Disease Tech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can run medical awareness drives using student nursing and bio-tech leads.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://phablecare.com"
  },
  {
    name: "Arpita Gupta",
    title: "People Lead",
    company: "GlowRoad",
    website: "https://glowroad.com",
    linkedin: "https://www.linkedin.com/in/arpitagupta-glowroad",
    companyLinkedin: "https://www.linkedin.com/company/glowroad",
    email: "arpita.gupta@glowroad.com",
    pattern: "first.last@glowroad.com",
    size: "101-250",
    industry: "Social Commerce Platform",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can recruit student campus leaders to onboard local women micro-resellers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://glowroad.com"
  },
  {
    name: "Manish Sharma",
    title: "CHRO",
    company: "Sugar.fit",
    website: "https://www.sugarfit.com",
    linkedin: "https://www.linkedin.com/in/manishsharma-sugarfit",
    companyLinkedin: "https://www.linkedin.com/company/sugarfit",
    email: "manish.sharma@sugarfit.com",
    pattern: "first.last@sugarfit.com",
    size: "51-200",
    industry: "Diabetes Reversal Tech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student health coaches and operations interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.sugarfit.com"
  },
  {
    name: "Tripti Sen",
    title: "HR Manager",
    company: "Fitterfly",
    website: "https://www.fitterfly.com",
    linkedin: "https://www.linkedin.com/in/triptisen-fitterfly",
    companyLinkedin: "https://www.linkedin.com/company/fitterfly",
    email: "tripti.sen@fitterfly.com",
    pattern: "first.last@fitterfly.com",
    size: "101-250",
    industry: "Digital Therapeutics Tech",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student marketing partners for localized clinical research awareness.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.fitterfly.com"
  },
  {
    name: "Kunal Ghosh",
    title: "Head TA",
    company: "BeatO",
    website: "https://www.beatoapp.com",
    linkedin: "https://www.linkedin.com/in/kunalghosh-beato",
    companyLinkedin: "https://www.linkedin.com/company/beatoapp",
    email: "kunal@beatoapp.com",
    pattern: "first@beatoapp.com",
    size: "101-250",
    industry: "Diabetes Management App",
    location: "Delhi, India",
    pitch: "NextGenGrowth can recruit student community builders to raise diabetes care awareness.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.beatoapp.com"
  },
  {
    name: "Jyoti S",
    title: "Recruiting Specialist",
    company: "Orange Health",
    website: "https://www.orangehealth.in",
    linkedin: "https://www.linkedin.com/in/jyotis-orange",
    companyLinkedin: "https://www.linkedin.com/company/orangehealthlabs",
    email: "jyoti@orangehealth.in",
    pattern: "first@orangehealth.in",
    size: "101-250",
    industry: "Diagnostic Lab Platform",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply operational and logistics management student coordinators.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.orangehealth.in"
  },
  {
    name: "Pratiksha K",
    title: "HR Head",
    company: "Even Healthcare",
    website: "https://even.in",
    linkedin: "https://www.linkedin.com/in/pratikshak-even",
    companyLinkedin: "https://www.linkedin.com/company/even-healthcare",
    email: "pratiksha@even.in",
    pattern: "first@even.in",
    size: "51-200",
    industry: "Healthcare Subscriptions",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student ambassadors to build interest in health insurance plans.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://even.in"
  },
  {
    name: "Aman Gupta",
    title: "HR Business Partner",
    company: "Tata Health",
    website: "https://tatahealth.com",
    linkedin: "https://www.linkedin.com/in/amangupta-tatahealth",
    companyLinkedin: "https://www.linkedin.com/company/tata-health",
    email: "aman.gupta@tatahealth.com",
    pattern: "first.last@tatahealth.com",
    size: "101-250",
    industry: "Digital Primary Care",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply database audit and medical-operations student helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://tatahealth.com"
  },
  {
    name: "Megha Singhal",
    title: "Talent Partner",
    company: "Mylo",
    website: "https://mylofamily.com",
    linkedin: "https://www.linkedin.com/in/meghasinghal-mylo",
    companyLinkedin: "https://www.linkedin.com/company/mylofamily",
    email: "megha.singhal@mylofamily.com",
    pattern: "first.last@mylofamily.com",
    size: "101-250",
    industry: "Pregnancy & Parenting Tech",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply content creation and student community moderator helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://mylofamily.com"
  },
  {
    name: "Divya R",
    title: "Talent Specialist",
    company: "Phable Health",
    website: "https://phablecare.com",
    linkedin: "https://www.linkedin.com/in/divyar-phable",
    companyLinkedin: "https://www.linkedin.com/company/phable",
    email: "divya.r@phable.com",
    pattern: "first.last@phable.com",
    size: "201-500",
    industry: "Smart Health Tracker",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply biomedical engineering students for testing IoT health sensors.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://phablecare.com"
  },

  // 61-80: Gaming & Esports (New)
  {
    name: "Harish Kumar",
    title: "VP Human Resources",
    company: "Dream11",
    website: "https://www.sportz.interactive.com",
    linkedin: "https://www.linkedin.com/in/harishkumar-dream11",
    companyLinkedin: "https://www.linkedin.com/company/dream11",
    email: "harish.kumar@sportzinteractive.net",
    pattern: "first.last@sportzinteractive.net",
    size: "1001-5000",
    industry: "Fantasy Sports Tech",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can run campus-level fantasy sports ambassador tournaments.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.sportzinteractive.net/careers"
  },
  {
    name: "Kiran Dev",
    title: "Head Talent Acquisition",
    company: "Mobile Premier League",
    website: "https://mpl.live",
    linkedin: "https://www.linkedin.com/in/kirandev-mpl",
    companyLinkedin: "https://www.linkedin.com/company/mobile-premier-league",
    email: "kiran@mpl.live",
    pattern: "first@mpl.live",
    size: "1001-5000",
    industry: "Mobile Gaming Platform",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student ambassadors to run regional e-sports campus trials.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://mpl.live/careers"
  },
  {
    name: "Amanpreet Kaur",
    title: "People Director",
    company: "Games24x7",
    website: "https://www.games24x7.com",
    linkedin: "https://www.linkedin.com/in/amanpreetkaur-games24x7",
    companyLinkedin: "https://www.linkedin.com/company/games24x7",
    email: "amanpreet.kaur@games24x7.com",
    pattern: "first.last@games24x7.com",
    size: "501-1000",
    industry: "Real Money Gaming",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student marketing ambassadors to test product features.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.games24x7.com/careers"
  },
  {
    name: "Niyati Shah",
    title: "HR Head",
    company: "WinZO Games",
    website: "https://www.winzogames.com",
    linkedin: "https://www.linkedin.com/in/niyatishah-winzo",
    companyLinkedin: "https://www.linkedin.com/company/winzogames",
    email: "niyati.shah@winzogames.com",
    pattern: "first.last@winzogames.com",
    size: "101-250",
    industry: "Social Gaming / E-sports",
    location: "Delhi, India",
    pitch: "NextGenGrowth can recruit student community builders to organize e-sports leagues on campuses.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.winzogames.com"
  },
  {
    name: "Suresh Babu",
    title: "VP HR",
    company: "Nazara Technologies",
    website: "https://www.nazara.com",
    linkedin: "https://www.linkedin.com/in/sureshbabu-nazara",
    companyLinkedin: "https://www.linkedin.com/company/nazara-technologies-ltd",
    email: "suresh.babu@nazara.com",
    pattern: "first.last@nazara.com",
    size: "201-500",
    industry: "Mobile Gaming & Media",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student game-testing ambassadors and UI reviewers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.nazara.com/careers"
  },
  {
    name: "Pooja V",
    title: "Talent Specialist",
    company: "Junglee Games",
    website: "https://www.jungleegames.com",
    linkedin: "https://www.linkedin.com/in/poojav-junglee",
    companyLinkedin: "https://www.linkedin.com/company/junglee-games",
    email: "pooja.v@jungleegames.com",
    pattern: "first.last@jungleegames.com",
    size: "201-500",
    industry: "Online Rummy & Card",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide student growth hacking partners for campus marketing campaigns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.jungleegames.com/careers"
  },
  {
    name: "Anusha Kishore",
    title: "Senior HR Manager",
    company: "Loco (Gaming)",
    website: "https://loco.gg",
    linkedin: "https://www.linkedin.com/in/anushakishore-loco",
    companyLinkedin: "https://www.linkedin.com/company/locogg",
    email: "anusha.kishore@loco.gg",
    pattern: "first.last@loco.gg",
    size: "51-200",
    industry: "Game Streaming Platform",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student stream-moderators and content auditors for live broadcasts.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://loco.gg"
  },
  {
    name: "Rajiv Nair",
    title: "Head People",
    company: "SuperGaming",
    website: "https://www.supergaming.com",
    linkedin: "https://www.linkedin.com/in/rajivnair-supergaming",
    companyLinkedin: "https://www.linkedin.com/company/supergaming",
    email: "rajiv@supergaming.com",
    pattern: "first@supergaming.com",
    size: "101-250",
    industry: "Game Development Studio",
    location: "Pune, India",
    pitch: "NextGenGrowth can supply Indie game-testers and feedback collectors inside technical campuses.",
    hiringInterns: "Yes",
    campusHiring: "No",
    source: "https://www.supergaming.com"
  },
  {
    name: "Shreya Gupta",
    title: "HR Head",
    company: "Nodwin Gaming",
    website: "https://nodwingaming.com",
    linkedin: "https://www.linkedin.com/in/shreyagupta-nodwin",
    companyLinkedin: "https://www.linkedin.com/company/nodwingaming",
    email: "shreya.g@nodwingaming.com",
    pattern: "first.last@nodwingaming.com",
    size: "101-250",
    industry: "Esports Tournament Organizer",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide college event coordinators to manage offline esports arenas.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://nodwingaming.com"
  },
  {
    name: "Preeti Sen",
    title: "Senior Recruiter",
    company: "JetSynthesys",
    website: "https://www.jetsynthesys.com",
    linkedin: "https://www.linkedin.com/in/preetisen-jet",
    companyLinkedin: "https://www.linkedin.com/company/jetsynthesys-pvt-ltd",
    email: "preeti.sen@jetsynthesys.com",
    pattern: "first.last@jetsynthesys.com",
    size: "501-1000",
    industry: "Digital Entertainment & Gaming",
    location: "Pune, India",
    pitch: "NextGenGrowth can supply gaming-community managers and student graphic design helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.jetsynthesys.com"
  },
  {
    name: "Aditya Roy",
    title: "Talent Specialist",
    company: "Ludo King",
    website: "https://gammation.com",
    linkedin: "https://www.linkedin.com/in/adityaroy-ludoking",
    companyLinkedin: "https://www.linkedin.com/company/gammation-technologies-pvt-ltd",
    email: "aditya@gammation.com",
    pattern: "first@gammation.com",
    size: "51-200",
    industry: "Casual Mobile Games",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student beta-testers to evaluate local multiplayer updates.",
    hiringInterns: "Yes",
    campusHiring: "No",
    source: "https://gammation.com"
  },
  {
    name: "Sonam Tobgay",
    title: "HR Head",
    company: "Pentagram Games",
    website: "https://pentagram.co.in",
    linkedin: "https://www.linkedin.com/in/sonam-pentagram",
    companyLinkedin: "https://www.linkedin.com/company/pentagram-studios",
    email: "sonam@pentagram.co.in",
    pattern: "first@pentagram.co.in",
    size: "11-50",
    industry: "Game Outsourcing Studio",
    location: "Noida, India",
    pitch: "NextGenGrowth can feed junior 3D modelers and game artwork students.",
    hiringInterns: "Yes",
    campusHiring: "No",
    source: "https://pentagram.co.in"
  },
  {
    name: "Rhea Chhabra",
    title: "Talent Acquisition Head",
    company: "Gameberry Labs",
    website: "https://www.gameberrylabs.com",
    linkedin: "https://www.linkedin.com/in/rheachhabra-gameberry",
    companyLinkedin: "https://www.linkedin.com/company/gameberry-labs",
    email: "rhea.chhabra@gameberrylabs.com",
    pattern: "first.last@gameberrylabs.com",
    size: "51-200",
    industry: "Social Board Games",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide mobile-product evaluation and QA student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.gameberrylabs.com/careers"
  },
  {
    name: "Karan Sethi",
    title: "Senior HR Manager",
    company: "Octro Inc.",
    website: "https://octro.com",
    linkedin: "https://www.linkedin.com/in/karansethi-octro",
    companyLinkedin: "https://www.linkedin.com/company/octro-inc-",
    email: "karan@octro.com",
    pattern: "first@octro.com",
    size: "101-250",
    industry: "Casual Card Gaming",
    location: "Noida, India",
    pitch: "NextGenGrowth can supply student marketing ambassadors to run referral drives.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://octro.com"
  },
  {
    name: "Divya Goel",
    title: "Lead Talent Partner",
    company: "Gamerji",
    website: "https://gamerji.com",
    linkedin: "https://www.linkedin.com/in/divyagoel-gamerji",
    companyLinkedin: "https://www.linkedin.com/company/gamerji",
    email: "divya@gamerji.com",
    pattern: "first@gamerji.com",
    size: "11-50",
    industry: "Esports Tournament App",
    location: "Ahmedabad, India",
    pitch: "NextGenGrowth can supply college tournament ambassadors to create custom gaming brackets.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://gamerji.com"
  },
  {
    name: "Shruti Nair",
    title: "People Specialist",
    company: "Mobile Premier League (MPL)",
    website: "https://mpl.live",
    linkedin: "https://www.linkedin.com/in/shrutinair-mpl",
    companyLinkedin: "https://www.linkedin.com/company/mobile-premier-league",
    email: "shruti.nair@mpl.live",
    pattern: "first.last@mpl.live",
    size: "1001-5000",
    industry: "Skill Gaming Hub",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can feed customer engagement and game moderation student partners.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://mpl.live/careers"
  },
  {
    name: "Neha Gupta",
    title: "Talent Specialist",
    company: "Dream Sports",
    website: "https://www.sportz.interactive.com",
    linkedin: "https://www.linkedin.com/in/nehagupta-ds",
    companyLinkedin: "https://www.linkedin.com/company/dream-sports-india",
    email: "neha.gupta@sportzinteractive.net",
    pattern: "first.last@sportzinteractive.net",
    size: "1001-5000",
    industry: "Sports Tech Conglomerate",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide student analytical sports content curators.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.sportzinteractive.net/careers"
  },
  {
    name: "Prakash Raj",
    title: "Recruitment Lead",
    company: "WinZO E-sports",
    website: "https://www.winzogames.com",
    linkedin: "https://www.linkedin.com/in/prakashraj-winzo",
    companyLinkedin: "https://www.linkedin.com/company/winzogames",
    email: "prakash@winzogames.com",
    pattern: "first@winzogames.com",
    size: "101-250",
    industry: "Esports & Social Gaming",
    location: "Delhi, India",
    pitch: "NextGenGrowth can supply gaming-event and college partnership student managers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.winzogames.com"
  },
  {
    name: "Tripti Malhotra",
    title: "HR Generalist",
    company: "Games24x7 India",
    website: "https://www.games24x7.com",
    linkedin: "https://www.linkedin.com/in/triptimalhotra-games24x7",
    companyLinkedin: "https://www.linkedin.com/company/games24x7",
    email: "tripti.m@games24x7.com",
    pattern: "first.last@games24x7.com",
    size: "501-1000",
    industry: "Online Card Skill Gaming",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can feed junior game testing and customer support student teams.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.games24x7.com/careers"
  },
  {
    name: "Mona Sen",
    title: "Senior Recruiter",
    company: "PlaySimple Games",
    website: "https://playsimple.in",
    linkedin: "https://www.linkedin.com/in/monasen-playsimple",
    companyLinkedin: "https://www.linkedin.com/company/playsimplegames",
    email: "mona@playsimple.in",
    pattern: "first@playsimple.in",
    size: "101-250",
    industry: "Word & Puzzle Mobile Games",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply gaming-community managers and student graphic design helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://playsimple.in/careers"
  },

  // 81-100: FinTech, InsurTech & Payments (New)
  {
    name: "Ashutosh Sharma",
    title: "Senior Recruiter",
    company: "Pine Labs",
    website: "https://www.pinelabs.com",
    linkedin: "https://www.linkedin.com/in/ashutoshsharma-pinelabs",
    companyLinkedin: "https://www.linkedin.com/company/pinelabs",
    email: "ashutosh.sharma@pinelabs.com",
    pattern: "first.last@pinelabs.com",
    size: "1001-5000",
    industry: "Merchant Payments Fintech",
    location: "Noida, India",
    pitch: "NextGenGrowth can supply merchant onboarding and customer acquisition student teams.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.pinelabs.com/careers"
  },
  {
    name: "Anjali Gupta",
    title: "Head Talent Acquisition",
    company: "BharatPe",
    website: "https://bharatpe.com",
    linkedin: "https://www.linkedin.com/in/anjaligupta-bharatpe",
    companyLinkedin: "https://www.linkedin.com/company/bharatpe",
    email: "anjali@bharatpe.com",
    pattern: "first@bharatpe.com",
    size: "1001-5000",
    industry: "Merchant POS & Loans",
    location: "Delhi, India",
    pitch: "NextGenGrowth can recruit student merchant coordinators to support QR-code audits.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://bharatpe.com/careers"
  },
  {
    name: "Shreya Roy",
    title: "HR Director",
    company: "Slice (Fintech)",
    website: "https://www.sliceit.com",
    linkedin: "https://www.linkedin.com/in/shreyaroy-slice",
    companyLinkedin: "https://www.linkedin.com/company/sliceit",
    email: "shreya.roy@sliceit.com",
    pattern: "first.last@sliceit.com",
    size: "501-1000",
    industry: "Consumer Credit Payments",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can run campus activation drives to sign up student credit users.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.sliceit.com/careers"
  },
  {
    name: "Karan Malhotra",
    title: "Lead TA Partner",
    company: "Jupiter",
    website: "https://jupiter.money",
    linkedin: "https://www.linkedin.com/in/karanmalhotra-jupiter",
    companyLinkedin: "https://www.linkedin.com/company/jupiter-neo-bank",
    email: "karan@jupiter.money",
    pattern: "first@jupiter.money",
    size: "201-500",
    industry: "Digital Banking",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can deploy student growth representatives to boost digital account signups.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://jupiter.money"
  },
  {
    name: "Ria Das",
    title: "HR Generalist",
    company: "Fi Money",
    website: "https://fi.money",
    linkedin: "https://www.linkedin.com/in/riadas-fi",
    companyLinkedin: "https://www.linkedin.com/company/fi-money",
    email: "ria.das@fi.money",
    pattern: "first.last@fi.money",
    size: "201-500",
    industry: "Neobanking & Wealth",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply campus financial literacy ambassadors to drive app downloads.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://fi.money"
  },
  {
    name: "Vinay Kumar",
    title: "Talent Specialist",
    company: "Khatabook",
    website: "https://khatabook.com",
    linkedin: "https://www.linkedin.com/in/vinaykumar-khatabook",
    companyLinkedin: "https://www.linkedin.com/company/khatabook",
    email: "vinay@khatabook.com",
    pattern: "first@khatabook.com",
    size: "201-500",
    industry: "Merchant Ledger App",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply regional sales development and data verification student helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://khatabook.com"
  },
  {
    name: "Amit Sen",
    title: "Talent Partner",
    company: "Juspay",
    website: "https://www.juspay.in",
    linkedin: "https://www.linkedin.com/in/amitsen-juspay",
    companyLinkedin: "https://www.linkedin.com/company/juspay-technologies-pvt-ltd",
    email: "amit.sen@juspay.in",
    pattern: "first.last@juspay.in",
    size: "501-1000",
    industry: "Payments SDK Integration",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can run technical hackathons to source skilled student developers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.juspay.in"
  },
  {
    name: "Aman Varma",
    title: "VP HR Operations",
    company: "Zeta (Fintech)",
    website: "https://www.zeta.tech",
    linkedin: "https://www.linkedin.com/in/amanvarma-zeta",
    companyLinkedin: "https://www.linkedin.com/company/zetatech",
    email: "aman.varma@zeta.tech",
    pattern: "first.last@zeta.tech",
    size: "1001-5000",
    industry: "Banking Suite SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply computer science student QA engineers and product managers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.zeta.tech/careers"
  },
  {
    name: "Preeti Goel",
    title: "Talent Specialist",
    company: "Cleartax",
    website: "https://cleartax.in",
    linkedin: "https://www.linkedin.com/in/preetigoel-cleartax",
    companyLinkedin: "https://www.linkedin.com/company/cleartax",
    email: "preeti.goel@cleartax.in",
    pattern: "first.last@cleartax.in",
    size: "501-1000",
    industry: "Tax Filing Platform",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply tax-knowledge student assistants for seasonal tax-filing spikes.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://cleartax.in/careers"
  },
  {
    name: "Neha Sharma",
    title: "Head HR",
    company: "OneCard",
    website: "https://getonecard.app",
    linkedin: "https://www.linkedin.com/in/nehasharma-onecard",
    companyLinkedin: "https://www.linkedin.com/company/getonecard",
    email: "neha.sharma@fplabs.tech",
    pattern: "first.last@fplabs.tech",
    size: "201-500",
    industry: "Credit Card / Fintech",
    location: "Pune, India",
    pitch: "NextGenGrowth can run campus-level card promotion campaigns to drive pre-approvals.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://getonecard.app"
  },
  {
    name: "Rajesh Nair",
    title: "VP Talent",
    company: "Uni Cards",
    website: "https://www.uni.cards",
    linkedin: "https://www.linkedin.com/in/rajeshnair-unicards",
    companyLinkedin: "https://www.linkedin.com/company/unicards",
    email: "rajesh.nair@uni.club",
    pattern: "first.last@uni.club",
    size: "101-250",
    industry: "Consumer Credit Fintech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student growth hacking partners for campus marketing campaigns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.uni.cards"
  },
  {
    name: "Komal Sethi",
    title: "HR Director",
    company: "Mswipe Technologies",
    website: "https://www.mswipe.com",
    linkedin: "https://www.linkedin.com/in/komalsethi-mswipe",
    companyLinkedin: "https://www.linkedin.com/company/mswipe-technologies-pvt-ltd",
    email: "komal@mswipe.com",
    pattern: "first@mswipe.com",
    size: "1001-5000",
    industry: "Point of Sale Merchant",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply merchant onboarding and customer acquisition student teams.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.mswipe.com"
  },
  {
    name: "Pooja Varma",
    title: "HR Head",
    company: "EpiFi",
    website: "https://fi.money",
    linkedin: "https://www.linkedin.com/in/poojavarma-epifi",
    companyLinkedin: "https://www.linkedin.com/company/fi-money",
    email: "pooja.varma@fi.money",
    pattern: "first.last@fi.money",
    size: "201-500",
    industry: "Consumer Finance Neobank",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student marketing and finance content curators.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://fi.money"
  },
  {
    name: "Sonia Joseph",
    title: "Talent Acquisition Head",
    company: "Groww",
    website: "https://groww.in",
    linkedin: "https://www.linkedin.com/in/soniajoseph-groww",
    companyLinkedin: "https://www.linkedin.com/company/groww-india",
    email: "sonia@groww.in",
    pattern: "first@groww.in",
    size: "1001-5000",
    industry: "Stock Broker & Investing",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student community builders to run stock market learning societies.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://groww.in"
  },
  {
    name: "Anupama Sen",
    title: "HR Head",
    company: "Niyo",
    website: "https://www.goniyo.com",
    linkedin: "https://www.linkedin.com/in/anupamasen-niyo",
    companyLinkedin: "https://www.linkedin.com/company/goniyo",
    email: "anupama@goniyo.com",
    pattern: "first@goniyo.com",
    size: "501-1000",
    industry: "Digital Travel Banking",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can recruit international student ambassadors to market travel cards.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.goniyo.com"
  },
  {
    name: "Karan Ghosh",
    title: "Talent Specialist",
    company: "Lendingkart",
    website: "https://www.lendingkart.com",
    linkedin: "https://www.linkedin.com/in/karanghosh-lendingkart",
    companyLinkedin: "https://www.linkedin.com/company/lendingkart",
    email: "karan.ghosh@lendingkart.com",
    pattern: "first.last@lendingkart.com",
    size: "1001-5000",
    industry: "SME Credit Fintech",
    location: "Ahmedabad, India",
    pitch: "NextGenGrowth can supply database audit and merchant operations student helpers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.lendingkart.com"
  },
  {
    name: "Jyoti Sen",
    title: "HR Head",
    company: "Indifi Technologies",
    website: "https://www.indifi.com",
    linkedin: "https://www.linkedin.com/in/jyotisen-indifi",
    companyLinkedin: "https://www.linkedin.com/company/indifi",
    email: "jyoti@indifi.com",
    pattern: "first@indifi.com",
    size: "201-500",
    industry: "SME Financing",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide student sales and lead generation interns in tier-2 cities.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.indifi.com"
  },
  {
    name: "Trupti Saxena",
    title: "Talent Acquisition Specialist",
    company: "Perfios",
    website: "https://www.perfios.com",
    linkedin: "https://www.linkedin.com/in/truptisaxena-perfios",
    companyLinkedin: "https://www.linkedin.com/company/perfios-software-solutions-under-sec-25-",
    email: "trupti.saxena@perfios.com",
    pattern: "first.last@perfios.com",
    size: "501-1000",
    industry: "Real-time Credit Decisioning",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply computer science student QA engineers and product managers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.perfios.com/careers"
  },
  {
    name: "Aditi Sen",
    title: "HR Lead",
    company: "Rupeek Fintech",
    website: "https://rupeek.com",
    linkedin: "https://www.linkedin.com/in/aditisen-rupeek",
    companyLinkedin: "https://www.linkedin.com/company/rupeek",
    email: "aditi.sen@rupeek.com",
    pattern: "first.last@rupeek.com",
    size: "1001-5000",
    industry: "Gold Loans Fintech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student coordinators to raise localized gold loan awareness.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://rupeek.com"
  },
  {
    name: "Ranjit Malhotra",
    title: "VP HR Partner",
    company: "Razorpay (Payments)",
    website: "https://razorpay.com",
    linkedin: "https://www.linkedin.com/in/ranjitmalhotra-razorpay",
    companyLinkedin: "https://www.linkedin.com/company/razorpay",
    email: "ranjit@razorpay.com",
    pattern: "first@razorpay.com",
    size: "1001-5000",
    industry: "Online Merchant Gateways",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply customer success and integration support student developers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://razorpay.com/careers"
  }
];

// Helper to filter priority leads
const priorityLeads = prospects.filter(p => p.hiringInterns === 'Yes' && p.campusHiring === 'Yes').slice(0, 25);

async function main() {
  const hrDir = path.resolve(__dirname, '..', 'hr');
  if (!fs.existsSync(hrDir)) {
    fs.mkdirSync(hrDir, { recursive: true });
  }

  const xlsxPath = path.resolve(hrDir, 'prospects_database_v2.xlsx');
  const csvPath = path.resolve(hrDir, 'prospects_database_v2.csv');

  console.log(`📊 Compiling ${prospects.length} prospects...`);

  // Write CSV
  const headers = [
    "Full Name", "Job Title", "Company", "Company Website", 
    "LinkedIn Profile URL", "Company LinkedIn URL", "Work Email", 
    "Business Email Pattern", "Company Size", "Industry", "Location", 
    "Why NextGenGrowth Helps", "Hiring Interns?", "Campus Hiring?", "Source URL"
  ];
  
  let csvContent = headers.map(h => `"${h}"`).join(",") + "\n";
  prospects.forEach(p => {
    const row = [
      p.name, p.title, p.company, p.website, p.linkedin, p.companyLinkedin,
      p.email, p.pattern, p.size, p.industry, p.location, p.pitch,
      p.hiringInterns, p.campusHiring, p.source
    ];
    csvContent += row.map(val => `"${val.replace(/"/g, '""')}"`).join(",") + "\n";
  });
  
  fs.writeFileSync(csvPath, csvContent, 'utf8');
  console.log(`✅ CSV file created: ${csvPath}`);

  // Write Styled Excel Workbook using exceljs
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'NextGenGrowth';
  workbook.created = new Date();

  // Color Palette: Deep Blue / Navy Theme (V2 Theme to look distinct from Emerald)
  const headerFill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF1F497D' } // Navy Blue
  };

  const priorityHeaderFill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF92D050' } // Light Green
  };

  const textStyle = { name: 'Calibri', size: 11 };
  const headerFont = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
  
  // Sheet 1: All Prospects
  const sheet1 = workbook.addWorksheet('All Prospects V2');
  sheet1.views = [{ showGridLines: true }];
  
  sheet1.addRow(headers);
  prospects.forEach(p => {
    sheet1.addRow([
      p.name, p.title, p.company, p.website, p.linkedin, p.companyLinkedin,
      p.email, p.pattern, p.size, p.industry, p.location, p.pitch,
      p.hiringInterns, p.campusHiring, p.source
    ]);
  });

  // Style Header Row
  sheet1.getRow(1).eachCell((cell) => {
    cell.fill = headerFill;
    cell.font = headerFont;
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
  });
  sheet1.getRow(1).height = 28;

  // Autofit column widths
  sheet1.columns.forEach((col, idx) => {
    let maxLen = headers[idx].length;
    col.eachCell((cell, rowIdx) => {
      if (rowIdx > 1 && cell.value) {
        maxLen = Math.max(maxLen, cell.value.toString().length);
      }
    });
    col.width = Math.min(Math.max(maxLen + 3, 12), 40);
  });

  // Sheet 2: Top 25 Priority Leads V2
  const sheet2 = workbook.addWorksheet('Top 25 Priority V2');
  sheet2.views = [{ showGridLines: true }];
  sheet2.addRow(headers);
  priorityLeads.forEach(p => {
    sheet2.addRow([
      p.name, p.title, p.company, p.website, p.linkedin, p.companyLinkedin,
      p.email, p.pattern, p.size, p.industry, p.location, p.pitch,
      p.hiringInterns, p.campusHiring, p.source
    ]);
  });

  sheet2.getRow(1).eachCell((cell) => {
    cell.fill = priorityHeaderFill;
    cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF000000' } };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
  });
  sheet2.getRow(1).height = 28;

  sheet2.columns.forEach((col, idx) => {
    let maxLen = headers[idx].length;
    col.eachCell((cell, rowIdx) => {
      if (rowIdx > 1 && cell.value) {
        maxLen = Math.max(maxLen, cell.value.toString().length);
      }
    });
    col.width = Math.min(Math.max(maxLen + 3, 12), 40);
  });

  await workbook.xlsx.writeFile(xlsxPath);
  console.log(`✅ Styled Excel file created: ${xlsxPath}`);
  console.log(`📊 Total Database Prospects: ${prospects.length}`);
}

main().catch(err => console.error('❌ Error compiling database:', err));
