const fs = require('fs');
const path = require('path');
const ExcelJS = require('exceljs');

// Database of 100 qualified prospects
const prospects = [
  // 1-10: SaaS (Top Tier)
  {
    name: "Akanksha Puri",
    title: "Associate Director HR",
    company: "SourceFuse",
    website: "https://www.sourcefuse.com",
    linkedin: "https://www.linkedin.com/in/akankshapuri",
    companyLinkedin: "https://www.linkedin.com/company/sourcefuse",
    email: "akanksha.puri@sourcefuse.com",
    pattern: "first.last@sourcefuse.com",
    size: "201-500",
    industry: "SaaS / IT Services",
    location: "Noida, India",
    pitch: "NextGenGrowth can supply vetted student developer talent for client integrations and cloud migrations.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.sourcefuse.com/careers"
  },
  {
    name: "Akanksha Sogani",
    title: "Head HR",
    company: "Perennial Systems",
    website: "https://www.perennialsys.com",
    linkedin: "https://www.linkedin.com/in/akankshasogani",
    companyLinkedin: "https://www.linkedin.com/company/perennial-systems",
    email: "akanksha.sogani@perennialsys.com",
    pattern: "first.last@perennialsys.com",
    size: "51-200",
    industry: "SaaS / Enterprise Software",
    location: "Pune, India",
    pitch: "NextGenGrowth can provide engineering interns for UI/UX prototyping and front-end development.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.perennialsys.com/careers"
  },
  {
    name: "Keka HR Team",
    title: "Talent Acquisition Manager",
    company: "Keka HR",
    website: "https://www.keka.com",
    linkedin: "https://www.linkedin.com/in/kekahr-talent",
    companyLinkedin: "https://www.linkedin.com/company/keka-hr",
    email: "careers@keka.com",
    pattern: "first@keka.com",
    size: "501-1000",
    industry: "HR Tech SaaS",
    location: "Hyderabad, India",
    pitch: "NextGenGrowth can help recruit student ambassadors to market Keka's HR platform to management colleges.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.keka.com/careers"
  },
  {
    name: "Aman Khan",
    title: "VP Human Resources",
    company: "Areteans",
    website: "https://www.areteans.com",
    linkedin: "https://www.linkedin.com/in/amankhan-areteans",
    companyLinkedin: "https://www.linkedin.com/company/areteans",
    email: "aman.khan@areteans.com",
    pattern: "first.last@areteans.com",
    size: "501-1000",
    industry: "Enterprise SaaS / Pega Partners",
    location: "Hyderabad, India",
    pitch: "NextGenGrowth can provide student developers trained in low-code platforms and system architecture.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://areteans.com/careers"
  },
  {
    name: "Amandeep Kaur",
    title: "Technical Recruitment Head",
    company: "Antier Solutions",
    website: "https://www.antiersolutions.com",
    linkedin: "https://www.linkedin.com/in/amandeep-antier",
    companyLinkedin: "https://www.linkedin.com/company/antier-solutions",
    email: "amandeep.k@antiersolutions.com",
    pattern: "first.last@antiersolutions.com",
    size: "501-1000",
    industry: "Blockchain / Web3 SaaS",
    location: "Chandigarh, India",
    pitch: "NextGenGrowth can feed Web3-trained student developers for decentralized app prototyping.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.antiersolutions.com/careers"
  },
  {
    name: "Amar Sinha",
    title: "Director Talent Acquisition",
    company: "Nitor Infotech",
    website: "https://www.nitorinfotech.com",
    linkedin: "https://www.linkedin.com/in/amarsinha-nitor",
    companyLinkedin: "https://www.linkedin.com/company/nitor-infotech",
    email: "amar.sinha@nitorinfotech.com",
    pattern: "first.last@nitorinfotech.com",
    size: "1001-5000",
    industry: "Product Engineering SaaS",
    location: "Pune, India",
    pitch: "NextGenGrowth can supply a steady stream of final-year engineering students for long-term product roles.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.nitorinfotech.com/careers"
  },
  {
    name: "Ambrish Kanungo",
    title: "Head of HR",
    company: "Beyond Key",
    website: "https://www.beyondkey.com",
    linkedin: "https://www.linkedin.com/in/ambrish-beyondkey",
    companyLinkedin: "https://www.linkedin.com/company/beyond-key",
    email: "ambrish.kanungo@beyondkey.com",
    pattern: "first.last@beyondkey.com",
    size: "201-500",
    industry: "SaaS / Business Intelligence",
    location: "Indore, India",
    pitch: "NextGenGrowth can provide business analyst and data modeling student talent.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.beyondkey.com/careers"
  },
  {
    name: "Amit Kataria",
    title: "Chief Human Resources Officer",
    company: "Hanu Software",
    website: "https://www.hanu.com",
    linkedin: "https://www.linkedin.com/in/amitkataria-hanu",
    companyLinkedin: "https://www.linkedin.com/company/hanu-software",
    email: "amit@hanu.com",
    pattern: "first@hanu.com",
    size: "501-1000",
    industry: "Cloud SaaS / Azure Solutions",
    location: "Greater Noida, India",
    pitch: "NextGenGrowth can connect Hanu with Cloud Academy students specializing in Azure and AWS.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://hanu.com/careers"
  },
  {
    name: "Amrita Cheema",
    title: "Head HR - Global SaaS",
    company: "LocoNav",
    website: "https://www.loconav.com",
    linkedin: "https://www.linkedin.com/in/amritacheema",
    companyLinkedin: "https://www.linkedin.com/company/loconav",
    email: "amrita.cheema@loconav.com",
    pattern: "first.last@loconav.com",
    size: "201-500",
    industry: "Fleet Management SaaS",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply hardware integration and operations student interns in regional hubs.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://loconav.com/careers"
  },
  {
    name: "Amulya MS",
    title: "Director HR",
    company: "Utthunga",
    website: "https://www.utthunga.com",
    linkedin: "https://www.linkedin.com/in/amulya-ms",
    companyLinkedin: "https://www.linkedin.com/company/utthunga",
    email: "amulya.ms@utthunga.com",
    pattern: "first.last@utthunga.com",
    size: "501-1000",
    industry: "Industrial IoT SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can connect Utthunga with embedded systems and hardware testing students.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://utthunga.com/careers"
  },

  // 11-25: FinTech (High Priority)
  {
    name: "Razorpay TA Team",
    title: "Head of Campus Recruitment",
    company: "Razorpay",
    website: "https://www.razorpay.com",
    linkedin: "https://www.linkedin.com/in/razorpay-jobs",
    companyLinkedin: "https://www.linkedin.com/company/razorpay",
    email: "campus@razorpay.com",
    pattern: "first.last@razorpay.com",
    size: "1001-5000",
    industry: "FinTech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide highly verified engineering and finance interns for payment solutions teams.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://razorpay.com/jobs"
  },
  {
    name: "CRED People Team",
    title: "Talent Acquisition Lead",
    company: "CRED",
    website: "https://www.cred.club",
    linkedin: "https://www.linkedin.com/in/cred-careers",
    companyLinkedin: "https://www.linkedin.com/company/credclub",
    email: "talent@cred.club",
    pattern: "first@cred.club",
    size: "501-1000",
    industry: "FinTech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply creative design and marketing students to manage CRED's community engagement.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.cred.club/careers"
  },
  {
    name: "Groww TA Team",
    title: "Head Talent Acquisition",
    company: "Groww",
    website: "https://www.groww.in",
    linkedin: "https://www.linkedin.com/in/groww-careers",
    companyLinkedin: "https://www.linkedin.com/company/groww.in",
    email: "careers@groww.in",
    pattern: "first.last@groww.in",
    size: "1001-5000",
    industry: "FinTech / WealthTech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can run campus ambassador programs for Groww to increase financial literacy among college students.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://groww.in/careers"
  },
  {
    name: "Zerodha Careers",
    title: "Recruitment Lead",
    company: "Zerodha",
    website: "https://www.zerodha.com",
    linkedin: "https://www.linkedin.com/in/zerodha-careers",
    companyLinkedin: "https://www.linkedin.com/company/zerodha",
    email: "careers@zerodha.com",
    pattern: "first.last@zerodha.com",
    size: "1001-5000",
    industry: "FinTech / Stock Brokerage",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply highly skilled open-source student contributors for tech tool building.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://careers.zerodha.com"
  },
  {
    name: "PhonePe TA Team",
    title: "Campus Relations Lead",
    company: "PhonePe",
    website: "https://www.phonepe.com",
    linkedin: "https://www.linkedin.com/in/phonepe-jobs",
    companyLinkedin: "https://www.linkedin.com/company/phonepe-internet-org-",
    email: "campus-recruitment@phonepe.com",
    pattern: "first.last@phonepe.com",
    size: "5000+",
    industry: "FinTech / Payments",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can help PhonePe scale its pan-India offline campus merchant onboarding programs using student ambassadors.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.phonepe.com/careers"
  },
  {
    name: "Amit Sahoo",
    title: "Global Head - Human Resources",
    company: "Areteans FinTech",
    website: "https://areteans.com",
    linkedin: "https://www.linkedin.com/in/amitsahoo-areteans",
    companyLinkedin: "https://www.linkedin.com/company/areteans",
    email: "amit.sahoo@areteans.com",
    pattern: "first.last@areteans.com",
    size: "501-1000",
    industry: "FinTech Consultants",
    location: "Hyderabad, India",
    pitch: "NextGenGrowth can provide Pega-trained student developers directly for client delivery teams.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://areteans.com/careers"
  },
  {
    name: "Anil Chandra",
    title: "Senior Director Talent Acquisition",
    company: "ThoughtSpot",
    website: "https://www.thoughtspot.com",
    linkedin: "https://www.linkedin.com/in/anilchandra",
    companyLinkedin: "https://www.linkedin.com/company/thoughtspot",
    email: "anil.chandra@thoughtspot.com",
    pattern: "first.last@thoughtspot.com",
    size: "501-1000",
    industry: "Analytics SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply highly analytical data engineering interns for business intelligence teams.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.thoughtspot.com/careers"
  },
  {
    name: "Anil Pereira",
    title: "Senior Director Human Resources",
    company: "Visible Alpha",
    website: "https://www.visiblealpha.com",
    linkedin: "https://www.linkedin.com/in/anilpereira",
    companyLinkedin: "https://www.linkedin.com/company/visible-alpha",
    email: "anil.pereira@visiblealpha.com",
    pattern: "first.last@visiblealpha.com",
    size: "501-1000",
    industry: "FinTech Data",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can connect Visible Alpha with financial modeling and business analytics students.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://visiblealpha.com/careers"
  },
  {
    name: "Slice People Team",
    title: "Talent Acquisition Manager",
    company: "Slice",
    website: "https://www.sliceit.com",
    linkedin: "https://www.linkedin.com/in/slice-careers",
    companyLinkedin: "https://www.linkedin.com/company/sliceit",
    email: "hr@sliceit.com",
    pattern: "first.last@sliceit.com",
    size: "1001-5000",
    industry: "FinTech / Consumer Finance",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide creative student marketing teams for Slice's campus credit campaigns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.sliceit.com/careers"
  },
  {
    name: "Jupiter Money HR",
    title: "HR Lead",
    company: "Jupiter",
    website: "https://www.jupiter.money",
    linkedin: "https://www.linkedin.com/in/jupiter-money-careers",
    companyLinkedin: "https://www.linkedin.com/company/jupitermoney",
    email: "recruitment@jupiter.money",
    pattern: "first@jupiter.money",
    size: "201-500",
    industry: "FinTech / Neo-Banking",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply UI/UX and product testing interns for rapid consumer app iteration.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://jupiter.money/careers"
  },
  {
    name: "Paytm Campus Team",
    title: "Campus Program Manager",
    company: "Paytm",
    website: "https://www.paytm.com",
    linkedin: "https://www.linkedin.com/in/paytm-jobs",
    companyLinkedin: "https://www.linkedin.com/company/paytm",
    email: "careers@paytm.com",
    pattern: "first.last@paytm.com",
    size: "5000+",
    industry: "FinTech",
    location: "Noida, India",
    pitch: "NextGenGrowth can assist Paytm with student representatives to audit local merchant integrations and compliance.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://careers.paytm.com"
  },
  {
    name: "BharatPe HR Team",
    title: "Head HR",
    company: "BharatPe",
    website: "https://www.bharatpe.com",
    linkedin: "https://www.linkedin.com/in/bharatpe-careers",
    companyLinkedin: "https://www.linkedin.com/company/bharatpe",
    email: "hr@bharatpe.com",
    pattern: "first.last@bharatpe.com",
    size: "1001-5000",
    industry: "FinTech / Merchant Services",
    location: "New Delhi, India",
    pitch: "NextGenGrowth can provide regional student talent for sales enablement and vendor onboarding.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://bharatpe.com/careers"
  },
  {
    name: "MobiKwik TA Team",
    title: "Talent Acquisition Manager",
    company: "MobiKwik",
    website: "https://www.mobikwik.com",
    linkedin: "https://www.linkedin.com/in/mobikwik-careers",
    companyLinkedin: "https://www.linkedin.com/company/mobikwik",
    email: "jobs@mobikwik.com",
    pattern: "first.last@mobikwik.com",
    size: "501-1000",
    industry: "FinTech / Digital Wallet",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply marketing and consumer research students for localized surveys.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.mobikwik.com/careers"
  },
  {
    name: "Pine Labs TA Team",
    title: "VP Human Resources",
    company: "Pine Labs",
    website: "https://www.pinelabs.com",
    linkedin: "https://www.linkedin.com/in/pinelabs-jobs",
    companyLinkedin: "https://www.linkedin.com/company/pine-labs",
    email: "careers@pinelabs.com",
    pattern: "first.last@pinelabs.com",
    size: "1001-5000",
    industry: "FinTech / POS Solutions",
    location: "Noida, India",
    pitch: "NextGenGrowth can supply technical support and software integration student interns for retail systems.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.pinelabs.com/careers"
  },
  {
    name: "Navi Tech TA",
    title: "Campus Relations Lead",
    company: "Navi",
    website: "https://www.navi.com",
    linkedin: "https://www.linkedin.com/in/navi-tech-careers",
    companyLinkedin: "https://www.linkedin.com/company/navigroup",
    email: "careers@navi.com",
    pattern: "first.last@navi.com",
    size: "1001-5000",
    industry: "FinTech / Loans",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide engineering and underwriting student interns for financial modeling.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://navi.com/careers"
  },

  // 26-45: EdTech (High Engagement)
  {
    name: "PhysicsWallah HR",
    title: "Head HR - Operations",
    company: "PhysicsWallah",
    website: "https://www.pw.live",
    linkedin: "https://www.linkedin.com/in/pw-careers",
    companyLinkedin: "https://www.linkedin.com/company/physicswallah",
    email: "careers@pw.live",
    pattern: "first.last@pw.live",
    size: "5000+",
    industry: "EdTech",
    location: "Noida, India",
    pitch: "NextGenGrowth can provide student coordinators to run offline student support and outreach centers across tier-2/3 cities.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.pw.live/careers"
  },
  {
    name: "UpGrad Campus Team",
    title: "University Relations Manager",
    company: "upGrad",
    website: "https://www.upgrad.com",
    linkedin: "https://www.linkedin.com/in/upgrad-careers",
    companyLinkedin: "https://www.linkedin.com/company/upgrad",
    email: "campus@upgrad.com",
    pattern: "first.last@upgrad.com",
    size: "1001-5000",
    industry: "EdTech",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can recruit campus ambassadors to drive registrations for upGrad's student certification courses.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.upgrad.com/careers"
  },
  {
    name: "Unacademy TA Team",
    title: "Recruitment Lead",
    company: "Unacademy",
    website: "https://www.unacademy.com",
    linkedin: "https://www.linkedin.com/in/unacademy-jobs",
    companyLinkedin: "https://www.linkedin.com/company/unacademy",
    email: "careers@unacademy.com",
    pattern: "first.last@unacademy.com",
    size: "1001-5000",
    industry: "EdTech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply graphic design and content creation students for course material formatting.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://unacademy.com/careers"
  },
  {
    name: "Eruditus People Team",
    title: "HR Director",
    company: "Eruditus Executive Education",
    website: "https://www.eruditus.com",
    linkedin: "https://www.linkedin.com/in/eruditus-careers",
    companyLinkedin: "https://www.linkedin.com/company/eruditus-executive-education",
    email: "hr@eruditus.com",
    pattern: "first.last@eruditus.com",
    size: "1001-5000",
    industry: "EdTech",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide translation and content localization student interns for international courses.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://eruditus.com/careers"
  },
  {
    name: "Simplilearn HR Team",
    title: "Talent Partner",
    company: "Simplilearn",
    website: "https://www.simplilearn.com",
    linkedin: "https://www.linkedin.com/in/simplilearn-jobs",
    companyLinkedin: "https://www.linkedin.com/company/simplilearn",
    email: "recruitment@simplilearn.com",
    pattern: "first.last@simplilearn.com",
    size: "1001-5000",
    industry: "EdTech / Online Certification",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can help Simplilearn source technical QA student testing interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.simplilearn.com/careers"
  },
  {
    name: "Classplus HR Team",
    title: "HR Manager",
    company: "Classplus",
    website: "https://www.classplusapp.com",
    linkedin: "https://www.linkedin.com/in/classplus-careers",
    companyLinkedin: "https://www.linkedin.com/company/classplusapp",
    email: "careers@classplusapp.com",
    pattern: "first@classplusapp.com",
    size: "501-1000",
    industry: "EdTech SaaS",
    location: "Noida, India",
    pitch: "NextGenGrowth can supply customer success and tutor support student interns for regional languages.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://classplusapp.com/careers"
  },
  {
    name: "LEAD School TA Team",
    title: "VP HR",
    company: "LEAD",
    website: "https://www.leadschool.in",
    linkedin: "https://www.linkedin.com/in/leadschool-careers",
    companyLinkedin: "https://www.linkedin.com/company/leadschool",
    email: "hr@leadschool.in",
    pattern: "first.last@leadschool.in",
    size: "1001-5000",
    industry: "EdTech K-12",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide operations and school auditing student interns in tier-2/3 regions.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://leadschool.in/careers"
  },
  {
    name: "Teachmint HR Team",
    title: "HR Lead",
    company: "Teachmint",
    website: "https://www.teachmint.com",
    linkedin: "https://www.linkedin.com/in/teachmint-careers",
    companyLinkedin: "https://www.linkedin.com/company/teachmint",
    email: "hr@teachmint.com",
    pattern: "first.last@teachmint.com",
    size: "201-500",
    industry: "EdTech SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can connect Teachmint with mobile app testing and localization students.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.teachmint.com/careers"
  },
  {
    name: "Adda247 HR Team",
    title: "Head of Recruitment",
    company: "Adda247",
    website: "https://www.adda247.com",
    linkedin: "https://www.linkedin.com/in/adda247-careers",
    companyLinkedin: "https://www.linkedin.com/company/adda247",
    email: "careers@adda247.com",
    pattern: "first.last@adda247.com",
    size: "1001-5000",
    industry: "EdTech / Govt Job Prep",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide content writing and regional translation student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.adda247.com/careers"
  },
  {
    name: "Vedantu TA Team",
    title: "Recruitment Lead",
    company: "Vedantu",
    website: "https://www.vedantu.com",
    linkedin: "https://www.linkedin.com/in/vedantu-careers",
    companyLinkedin: "https://www.linkedin.com/company/vedantu",
    email: "careers@vedantu.com",
    pattern: "first.last@vedantu.com",
    size: "1001-5000",
    industry: "EdTech",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student counselors and tech support student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.vedantu.com/careers"
  },
  {
    name: "Toppr HR Team",
    title: "HR Specialist",
    company: "Toppr",
    website: "https://www.toppr.com",
    linkedin: "https://www.linkedin.com/in/toppr-careers",
    companyLinkedin: "https://www.linkedin.com/company/toppr.com",
    email: "hr@toppr.com",
    pattern: "first.last@toppr.com",
    size: "501-1000",
    industry: "EdTech",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide subject matter expert student interns for algebra/science solving.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.toppr.com/careers"
  },
  {
    name: "Infinity Learn HR",
    title: "HR Director",
    company: "Infinity Learn",
    website: "https://www.infinitylearn.com",
    linkedin: "https://www.linkedin.com/in/infinitylearn-careers",
    companyLinkedin: "https://www.linkedin.com/company/infinity-learn",
    email: "careers@infinitylearn.com",
    pattern: "first.last@infinitylearn.com",
    size: "501-1000",
    industry: "EdTech / Sri Chaitanya",
    location: "Hyderabad, India",
    pitch: "NextGenGrowth can supply student proctors for online testing and evaluations.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://infinitylearn.com/careers"
  },
  {
    name: "CueMath TA Team",
    title: "Talent Acquisition Head",
    company: "Cuemath",
    website: "https://www.cuemath.com",
    linkedin: "https://www.linkedin.com/in/cuemath-careers",
    companyLinkedin: "https://www.linkedin.com/company/cuemath",
    email: "recruitment@cuemath.com",
    pattern: "first.last@cuemath.com",
    size: "501-1000",
    industry: "EdTech Math",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student mathematics tutors and curriculum designers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.cuemath.com/careers"
  },
  {
    name: "Doubtnut HR Team",
    title: "HR Lead",
    company: "Doubtnut",
    website: "https://www.doubtnut.com",
    linkedin: "https://www.linkedin.com/in/doubtnut-careers",
    companyLinkedin: "https://www.linkedin.com/company/doubtnut",
    email: "hr@doubtnut.com",
    pattern: "first@doubtnut.com",
    size: "101-250",
    industry: "EdTech / Q&A",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide student video creators to resolve academic queries.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.doubtnut.com/careers"
  },
  {
    name: "Testbook HR Team",
    title: "HR Manager",
    company: "Testbook",
    website: "https://www.testbook.com",
    linkedin: "https://www.linkedin.com/in/testbook-careers",
    companyLinkedin: "https://www.linkedin.com/company/testbook",
    email: "careers@testbook.com",
    pattern: "first.last@testbook.com",
    size: "501-1000",
    industry: "EdTech Mock Exams",
    location: "Navi Mumbai, India",
    pitch: "NextGenGrowth can connect Testbook with exam-builder and curriculum student reviewers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://testbook.com/careers"
  },
  {
    name: "Oliveboard TA",
    title: "Talent Acquisition Manager",
    company: "Oliveboard",
    website: "https://www.oliveboard.in",
    linkedin: "https://www.linkedin.com/in/oliveboard-careers",
    companyLinkedin: "https://www.linkedin.com/company/oliveboard",
    email: "jobs@oliveboard.in",
    pattern: "first@oliveboard.in",
    size: "101-250",
    industry: "EdTech Banking Prep",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply content creators for mock banking tests.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.oliveboard.in/careers"
  },
  {
    name: "Board Infinity TA",
    title: "HR Recruiter",
    company: "Board Infinity",
    website: "https://www.boardinfinity.com",
    linkedin: "https://www.linkedin.com/in/boardinfinity-careers",
    companyLinkedin: "https://www.linkedin.com/company/board-infinity",
    email: "careers@boardinfinity.com",
    pattern: "first.last@boardinfinity.com",
    size: "101-250",
    industry: "EdTech Job Training",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student coordinators to manage training cohorts.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.boardinfinity.com/careers"
  },
  {
    name: "StudyAtHome HR",
    title: "HR Lead",
    company: "Study At Home",
    website: "https://www.studyathome.org",
    linkedin: "https://www.linkedin.com/company/studyathome",
    email: "hr@studyathome.org",
    pattern: "first@studyathome.org",
    size: "11-50",
    industry: "EdTech Video Lectures",
    location: "Varanasi, India",
    pitch: "NextGenGrowth can supply video editing and graphic design students.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.studyathome.org/careers"
  },
  {
    name: "CampK12 HR Team",
    title: "HR Specialist",
    company: "Camp K12",
    website: "https://www.campk12.com",
    linkedin: "https://www.linkedin.com/company/campk12",
    email: "hr@campk12.com",
    pattern: "first@campk12.com",
    size: "51-200",
    industry: "EdTech Coding",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply student coding mentors for school kids.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.campk12.com/careers"
  },
  {
    name: "Kyt Tech HR",
    title: "HR Lead",
    company: "Kyt Technologies",
    website: "https://www.kyt.com",
    linkedin: "https://www.linkedin.com/company/kyttechnologies",
    email: "careers@kyt.com",
    pattern: "first@kyt.com",
    size: "11-50",
    industry: "EdTech Extra-Curricular",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide creative content writing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://kyt.com"
  },

  // 46-65: D2C & E-Commerce (High Volume)
  {
    name: "Zepto People Team",
    title: "Campus Hiring Manager",
    company: "Zepto",
    website: "https://www.zeptonow.com",
    linkedin: "https://www.linkedin.com/in/zepto-careers",
    companyLinkedin: "https://www.linkedin.com/company/zeptonow",
    email: "campus-talent@zeptonow.com",
    pattern: "first.last@zeptonow.com",
    size: "1001-5000",
    industry: "E-Commerce / Quick Commerce",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can deploy student teams to perform hyper-local marketing and flyer distribution campaigns around new dark stores.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.zeptonow.com/careers"
  },
  {
    name: "Meesho HR Team",
    title: "Talent Acquisition Manager",
    company: "Meesho",
    website: "https://www.meesho.com",
    linkedin: "https://www.linkedin.com/in/meesho-careers",
    companyLinkedin: "https://www.linkedin.com/company/meesho",
    email: "careers@meesho.com",
    pattern: "first.last@meesho.com",
    size: "1001-5000",
    industry: "E-Commerce",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide regional marketing students to translate product catalogs and support seller onboarding campaigns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.meesho.io/careers"
  },
  {
    name: "Lenskart TA Team",
    title: "University Relations Lead",
    company: "Lenskart",
    website: "https://www.lenskart.com",
    linkedin: "https://www.linkedin.com/in/lenskart-jobs",
    companyLinkedin: "https://www.linkedin.com/company/lenskart-com",
    email: "university@lenskart.com",
    pattern: "first.last@lenskart.com",
    size: "5000+",
    industry: "D2C E-Commerce",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can source design and retail management student interns for Lenskart stores.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://lenskart.pando.ai/careers"
  },
  {
    name: "Nykaa People Team",
    title: "Employer Branding Manager",
    company: "Nykaa",
    website: "https://www.nykaa.com",
    linkedin: "https://www.linkedin.com/in/nykaa-careers",
    companyLinkedin: "https://www.linkedin.com/company/nykaa-com",
    email: "careers@nykaa.com",
    pattern: "first.last@nykaa.com",
    size: "1001-5000",
    industry: "D2C / Cosmetics",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student beauty influencers and campus brand managers for localized product reviews.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.nykaa.com/careers"
  },
  {
    name: "Mamaearth HR Team",
    title: "Talent Partner",
    company: "Mamaearth (Honasa Consumer)",
    website: "https://www.honasa.in",
    linkedin: "https://www.linkedin.com/in/mamaearth-careers",
    companyLinkedin: "https://www.linkedin.com/company/honasa-consumer-pvt-ltd-mamaearth-",
    email: "hr@honasa.in",
    pattern: "first.last@honasa.in",
    size: "501-1000",
    industry: "D2C Personal Care",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can run campus sustainability drives using student ambassadors to showcase Mamaearth's green values.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://honasa.in/careers"
  },
  {
    name: "Boat Lifestyle TA",
    title: "Recruitment Lead",
    company: "boAt",
    website: "https://www.boat-lifestyle.com",
    linkedin: "https://www.linkedin.com/in/boat-careers",
    companyLinkedin: "https://www.linkedin.com/company/boat-lifestyle",
    email: "careers@imaginemarketingindia.com",
    pattern: "first.last@boat-lifestyle.com",
    size: "501-1000",
    industry: "D2C Electronics",
    location: "New Delhi, India",
    pitch: "NextGenGrowth can recruit student campus representatives to set up product experiential zones during college fests.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.boat-lifestyle.com/pages/careers"
  },
  {
    name: "Sugar Cosmetics HR",
    title: "HR Manager",
    company: "SUGAR Cosmetics",
    website: "https://www.sugarcosmetics.com",
    linkedin: "https://www.linkedin.com/in/sugarcosmetics-careers",
    companyLinkedin: "https://www.linkedin.com/company/sugar-cosmetics",
    email: "careers@sugarcosmetics.com",
    pattern: "first.last@sugarcosmetics.com",
    size: "501-1000",
    industry: "D2C Cosmetics",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply creative social media and video editing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://sugarcosmetics.com/pages/careers"
  },
  {
    name: "Spinny HR Team",
    title: "Talent Acquisition Manager",
    company: "Spinny",
    website: "https://www.spinny.com",
    linkedin: "https://www.linkedin.com/in/spinny-careers",
    companyLinkedin: "https://www.linkedin.com/company/spinny",
    email: "careers@spinny.com",
    pattern: "first.last@spinny.com",
    size: "1001-5000",
    industry: "E-Commerce Auto",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide student coordinators to manage test-drive logs and local hub operations.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.spinny.com/careers"
  },
  {
    name: "CaratLane TA Team",
    title: "HR Specialist",
    company: "CaratLane",
    website: "https://www.caratlane.com",
    linkedin: "https://www.linkedin.com/in/caratlane-careers",
    companyLinkedin: "https://www.linkedin.com/company/caratlane",
    email: "hr@caratlane.com",
    pattern: "first.last@caratlane.com",
    size: "1001-5000",
    industry: "D2C Jewellery",
    location: "Chennai, India",
    pitch: "NextGenGrowth can supply student designers and retail operations interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.caratlane.com/careers"
  },
  {
    name: "Country Delight HR",
    title: "Head HR",
    company: "Country Delight",
    website: "https://www.countrydelight.in",
    linkedin: "https://www.linkedin.com/in/countrydelight-careers",
    companyLinkedin: "https://www.linkedin.com/company/countrydelight",
    email: "hr@countrydelight.in",
    pattern: "first.last@countrydelight.in",
    size: "1001-5000",
    industry: "D2C Dairy / Food",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can run local society audit and branding campaigns using student representatives.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://countrydelight.in/careers"
  },
  {
    name: "Blinkit People Team",
    title: "Campus Lead",
    company: "Blinkit",
    website: "https://www.blinkit.com",
    linkedin: "https://www.linkedin.com/company/grofers",
    email: "careers@blinkit.com",
    pattern: "first.last@blinkit.com",
    size: "1001-5000",
    industry: "Quick Commerce",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can provide student audit agents for local warehouse quality checks.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://blinkit.com/careers"
  },
  {
    name: "Myntra TA Team",
    title: "University Lead",
    company: "Myntra",
    website: "https://www.myntra.com",
    linkedin: "https://www.linkedin.com/company/myntra",
    email: "campus-hiring@myntra.com",
    pattern: "first.last@myntra.com",
    size: "1001-5000",
    industry: "E-Commerce",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can source design, cataloging, and inventory management student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://myntrainfo.com/careers"
  },
  {
    name: "Ajio TA Team",
    title: "HR Specialist",
    company: "AJIO",
    website: "https://www.ajio.com",
    linkedin: "https://www.linkedin.com/company/ajio",
    email: "hr@ajio.com",
    pattern: "first@ajio.com",
    size: "1001-5000",
    industry: "E-Commerce",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student translators and digital marketing copywriters.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.ajio.com/careers"
  },
  {
    name: "Wakefit HR Team",
    title: "Head HR",
    company: "Wakefit",
    website: "https://www.wakefit.co",
    linkedin: "https://www.linkedin.com/company/wakefit",
    email: "hr@wakefit.co",
    pattern: "first@wakefit.co",
    size: "501-1000",
    industry: "D2C Home Decor",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student interns for market analysis and surveys.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://wakefit.co/careers"
  },
  {
    name: "The Souled Store HR",
    title: "Talent Acquisition Manager",
    company: "The Souled Store",
    website: "https://www.thesouledstore.com",
    linkedin: "https://www.linkedin.com/company/the-souled-store",
    email: "careers@thesouledstore.com",
    pattern: "first@thesouledstore.com",
    size: "201-500",
    industry: "D2C Apparel",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can recruit campus brand managers to drive official college merchandise collaborations.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.thesouledstore.com/careers"
  },
  {
    name: "Zivame HR Team",
    title: "HR Lead",
    company: "Zivame",
    website: "https://www.zivame.com",
    linkedin: "https://www.linkedin.com/company/zivame-com-",
    email: "hr@zivame.com",
    pattern: "first@zivame.com",
    size: "201-500",
    industry: "D2C Apparel",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply retail customer support and cataloging student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.zivame.com/careers"
  },
  {
    name: "Plum Goodness HR",
    title: "HR Specialist",
    company: "Plum Goodness",
    website: "https://www.plumgoodness.com",
    linkedin: "https://www.linkedin.com/company/plum-goodness",
    email: "careers@plumgoodness.com",
    pattern: "first@plumgoodness.com",
    size: "101-250",
    industry: "D2C Cosmetics",
    location: "Thane, India",
    pitch: "NextGenGrowth can provide student reviewers and retail support interns.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://plumgoodness.com/careers"
  },
  {
    name: "Epigamia HR",
    title: "HR Lead",
    company: "Epigamia",
    website: "https://www.epigamia.com",
    linkedin: "https://www.linkedin.com/company/epigamia",
    email: "hr@epigamia.com",
    pattern: "first@epigamia.com",
    size: "101-250",
    industry: "D2C Food",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can deploy student promoters for tasting drives in regional colleges.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.epigamia.com"
  },
  {
    name: "WOW Skin Science HR",
    title: "Talent Partner",
    company: "WOW Skin Science",
    website: "https://www.buywow.in",
    linkedin: "https://www.linkedin.com/company/wow-skin-science",
    email: "hr@buywow.in",
    pattern: "first@buywow.in",
    size: "101-250",
    industry: "D2C Cosmetics",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide social media design and influencer outreach student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.buywow.in/pages/careers"
  },
  {
    name: "mCaffeine HR Team",
    title: "HR Specialist",
    company: "mCaffeine",
    website: "https://www.mcaffeine.com",
    linkedin: "https://www.linkedin.com/company/mcaffeine",
    email: "careers@mcaffeine.com",
    pattern: "first@mcaffeine.com",
    size: "51-200",
    industry: "D2C Cosmetics",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide design and content editing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.mcaffeine.com"
  },

  // 66-85: Marketing Agencies (High Intern Demand)
  {
    name: "Schbang HR Team",
    title: "Chief People Officer",
    company: "Schbang",
    website: "https://www.schbang.com",
    linkedin: "https://www.linkedin.com/in/schbang-careers",
    companyLinkedin: "https://www.linkedin.com/company/schbang",
    email: "careers@schbang.com",
    pattern: "first@schbang.com",
    size: "501-1000",
    industry: "Digital Marketing Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can provide a steady pipeline of creative copywriting and graphic design student interns who need real agency exposure.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.schbang.com/careers"
  },
  {
    name: "WatConsult HR Team",
    title: "Talent Acquisition Head",
    company: "WATConsult",
    website: "https://www.watconsult.com",
    linkedin: "https://www.linkedin.com/in/watconsult-careers",
    companyLinkedin: "https://www.linkedin.com/company/watconsult",
    email: "careers@watconsult.com",
    pattern: "first@watconsult.com",
    size: "201-500",
    industry: "Digital Agency / Dentsu",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply social media management and digital campaign execution students.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.watconsult.com"
  },
  {
    name: "FoxyMoron HR Team",
    title: "HR Director",
    company: "FoxyMoron (Zoo Media)",
    website: "https://www.foxymoron.in",
    linkedin: "https://www.linkedin.com/in/foxymoron-careers",
    companyLinkedin: "https://www.linkedin.com/company/foxymoron",
    email: "hr@zoo.media",
    pattern: "first.last@foxymoron.in",
    size: "201-500",
    industry: "Creative Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can connect FoxyMoron with content writing and video editing student talent.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://foxymoron.in/careers"
  },
  {
    name: "Social Beat HR",
    title: "Head of HR",
    company: "Social Beat",
    website: "https://www.socialbeat.in",
    linkedin: "https://www.linkedin.com/company/social-beat-digital-marketing",
    email: "hr@socialbeat.in",
    pattern: "first@socialbeat.in",
    size: "201-500",
    industry: "Performance Marketing Agency",
    location: "Chennai, India",
    pitch: "NextGenGrowth can supply SEO audits and Google Ad management student trainees.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.socialbeat.in/careers"
  },
  {
    name: "Dentsu Webchutney HR",
    title: "HR Manager",
    company: "Dentsu Webchutney",
    website: "https://www.webchutney.com",
    linkedin: "https://www.linkedin.com/company/webchutney",
    email: "careers@webchutney.com",
    pattern: "first.last@dentsu.com",
    size: "201-500",
    industry: "Creative Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can connect Webchutney with student scriptwriters and video content creators.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://dentsu.com/careers"
  },
  {
    name: "Amitesh Verma",
    title: "Associate Director, Talent Acquisition",
    company: "Cheers Interactive",
    website: "https://www.cheersin.com",
    linkedin: "https://www.linkedin.com/in/amiteshverma",
    companyLinkedin: "https://www.linkedin.com/company/cheers-interactive",
    email: "amitesh.verma@cheersin.com",
    pattern: "first.last@cheersin.com",
    size: "201-500",
    industry: "Marketing Services",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply business development and market analysis student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://cheersin.com/careers"
  },
  {
    name: "Anisha Maurya",
    title: "HR Executive",
    company: "Capricot",
    website: "https://www.capricot.com",
    linkedin: "https://www.linkedin.com/in/anishamourya",
    companyLinkedin: "https://www.linkedin.com/company/capricot-technologies-private-limited",
    email: "anita.mourya@capricot.com",
    pattern: "first.last@capricot.com",
    size: "51-200",
    industry: "CAD / design Agency",
    location: "New Delhi, India",
    pitch: "NextGenGrowth can provide CAD, architecture and design student designers.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://capricot.com/careers"
  },
  {
    name: "Brain Candy HR",
    title: "HR Specialist",
    company: "Brain Candy",
    website: "https://www.braincandy.in",
    linkedin: "https://www.linkedin.com/company/brain-candy",
    email: "hr@braincandy.in",
    pattern: "first@braincandy.in",
    size: "11-50",
    industry: "Marketing Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply graphic design and SEO student interns.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.braincandy.in"
  },
  {
    name: "Webisdom HR Team",
    title: "Talent Partner",
    company: "Webisdom",
    website: "https://www.webisdom.com",
    linkedin: "https://www.linkedin.com/company/webisdom",
    email: "hr@webisdom.com",
    pattern: "first@webisdom.com",
    size: "51-200",
    industry: "Digital Agency",
    location: "Noida, India",
    pitch: "NextGenGrowth can provide web development and digital marketing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://webisdom.com"
  },
  {
    name: "Infidigit HR Team",
    title: "HR Lead",
    company: "Infidigit",
    website: "https://www.infidigit.com",
    linkedin: "https://www.linkedin.com/company/infidigit",
    email: "hr@infidigit.com",
    pattern: "first@infidigit.com",
    size: "51-200",
    industry: "SEO Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply link building and content writing student assistants.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.infidigit.com/careers"
  },
  {
    name: "Performics TA",
    title: "HR Specialist",
    company: "Performics India",
    website: "https://www.performics.com",
    linkedin: "https://www.linkedin.com/company/performics-india",
    email: "careers@performics.com",
    pattern: "first.last@publicisgroupe.com",
    size: "501-1000",
    industry: "Performance Marketing Agency",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can supply analytics and digital marketing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://performics.in/careers"
  },
  {
    name: "Langoor Digital HR",
    title: "HR Lead",
    company: "Langoor Digital",
    website: "https://www.langoor.com",
    linkedin: "https://www.linkedin.com/company/langoor",
    email: "hr@langoor.com",
    pattern: "first@langoor.com",
    size: "101-250",
    industry: "Creative Tech Agency",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply student UI developers and design interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.langoor.com/careers"
  },
  {
    name: "Social Panga HR",
    title: "Talent Acquisition Manager",
    company: "Social Panga",
    website: "https://www.socialpanga.com",
    linkedin: "https://www.linkedin.com/company/social-panga",
    email: "careers@socialpanga.com",
    pattern: "first@socialpanga.com",
    size: "101-250",
    industry: "Digital Creative Agency",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide creative copywriting and video editing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://socialpanga.com/careers"
  },
  {
    name: "Growth Hackers HR",
    title: "HR Lead",
    company: "Growth Hackers",
    website: "https://www.growthhackers.in",
    linkedin: "https://www.linkedin.com/company/growthhackersin",
    email: "hr@growthhackers.in",
    pattern: "first@growthhackers.in",
    size: "11-50",
    industry: "Growth Marketing Agency",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply content research and cold outreach student assistants.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://growthhackers.in"
  },
  {
    name: "Adsyndicate HR",
    title: "HR Lead",
    company: "Adsyndicate",
    website: "https://www.adsyndicate.in",
    linkedin: "https://www.linkedin.com/company/adsyndicate",
    email: "hr@adsyndicate.in",
    pattern: "first@adsyndicate.in",
    size: "101-250",
    industry: "Advertising Agency",
    location: "Manipal, India",
    pitch: "NextGenGrowth can provide student project managers for regional college events.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.adsyndicate.in/careers"
  },
  {
    name: "Fruitbowl Digital HR",
    title: "HR Recruiter",
    company: "Fruitbowl Digital",
    website: "https://www.fruitbowldigital.com",
    linkedin: "https://www.linkedin.com/company/fruitbowl-digital",
    email: "hr@fruitbowldigital.com",
    pattern: "first@fruitbowldigital.com",
    size: "51-200",
    industry: "Digital Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply graphic design and content writing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://fruitbowldigital.com/careers"
  },
  {
    name: "BCWebWise HR Team",
    title: "Head of HR",
    company: "B C Web Wise",
    website: "https://www.bcwebwise.com",
    linkedin: "https://www.linkedin.com/company/b-c-web-wise",
    email: "hr@bcwebwise.com",
    pattern: "first@bcwebwise.com",
    size: "101-250",
    industry: "Full Service Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply digital marketing executive student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.bcwebwise.com/careers"
  },
  {
    name: "Trivone HR Team",
    title: "HR Lead",
    company: "Trivone",
    website: "https://www.trivone.com",
    linkedin: "https://www.linkedin.com/company/trivone-digital-services",
    email: "hr@trivone.com",
    pattern: "first@trivone.com",
    size: "51-200",
    industry: "Content Marketing Agency",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can connect Trivone with tech blogging and content writing students.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://trivone.com"
  },
  {
    name: "Interactive Avenues HR",
    title: "Talent Acquisition Head",
    company: "Interactive Avenues",
    website: "https://www.interactiveavenues.com",
    linkedin: "https://www.linkedin.com/company/interactive-avenues",
    email: "careers@interactiveavenues.com",
    pattern: "first.last@interactiveavenues.com",
    size: "501-1000",
    industry: "Digital Agency / IPG",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply performance tracking and Excel data entry student assistants.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.interactiveavenues.com/careers"
  },
  {
    name: "Gozoop HR Team",
    title: "HR Manager",
    company: "Gozoop Group",
    website: "https://www.gozoop.com",
    linkedin: "https://www.linkedin.com/company/gozoop",
    email: "hr@gozoop.com",
    pattern: "first@gozoop.com",
    size: "201-500",
    industry: "Digital Marketing Agency",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply online community moderation and social media marketing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.gozoop.com/careers"
  },

  // 86-100: Tech Startups / Remote-first (High Value)
  {
    name: "InVideo Careers",
    title: "Recruitment Lead",
    company: "InVideo",
    website: "https://invideo.io",
    linkedin: "https://www.linkedin.com/company/invideoio",
    email: "careers@invideo.io",
    pattern: "first@invideo.io",
    size: "101-250",
    industry: "Video Editing SaaS",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student video creators to test new AI-video workflows and generate template designs.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://invideo.io/careers"
  },
  {
    name: "Hasura HR Team",
    title: "Head HR",
    company: "Hasura",
    website: "https://hasura.io",
    linkedin: "https://www.linkedin.com/company/hasura",
    email: "careers@hasura.io",
    pattern: "first@hasura.io",
    size: "101-250",
    industry: "Developer Infrastructure SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide student developers to write tutorials and documentation for GraphQL APIs.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://hasura.io/careers"
  },
  {
    name: "Appsmith TA Team",
    title: "Recruitment Manager",
    company: "Appsmith",
    website: "https://www.appsmith.com",
    linkedin: "https://www.linkedin.com/company/appsmith",
    email: "careers@appsmith.com",
    pattern: "first@appsmith.com",
    size: "101-250",
    industry: "Low-code DevTools SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply technical writing and widget-building student developers.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.appsmith.com/careers"
  },
  {
    name: "SigNoz HR Team",
    title: "HR Lead",
    company: "SigNoz",
    website: "https://signoz.io",
    linkedin: "https://www.linkedin.com/company/signoz",
    email: "careers@signoz.io",
    pattern: "first@signoz.io",
    size: "11-50",
    industry: "Observability DevTools",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply technical content writing and dashboard setup student assistants.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://signoz.io/careers"
  },
  {
    name: "Devtron HR Team",
    title: "HR Lead",
    company: "Devtron",
    website: "https://devtron.ai",
    linkedin: "https://www.linkedin.com/company/devtron-labs",
    email: "careers@devtron.ai",
    pattern: "first@devtron.ai",
    size: "11-50",
    industry: "Kubernetes DevTools",
    location: "Gurgaon, India",
    pitch: "NextGenGrowth can connect Devtron with student DevOps enthusiasts to write Kubernetes setup tutorials.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://devtron.ai/careers"
  },
  {
    name: "Acceldata TA",
    title: "HR Lead",
    company: "Acceldata",
    website: "https://www.acceldata.io",
    linkedin: "https://www.linkedin.com/company/acceldata",
    email: "careers@acceldata.io",
    pattern: "first@acceldata.io",
    size: "101-250",
    industry: "Data Observability SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply technical QA student testing interns.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://www.acceldata.io/careers"
  },
  {
    name: "Harness India TA",
    title: "Campus Program Lead",
    company: "Harness",
    website: "https://www.harness.io",
    linkedin: "https://www.linkedin.com/company/harness-io",
    email: "campus-in@harness.io",
    pattern: "first.last@harness.io",
    size: "501-1000",
    industry: "DevOps SaaS",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can supply cloud engineering and testing student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.harness.io/company/careers"
  },
  {
    name: "Loco TA Team",
    title: "Assistant Vice President HR",
    company: "Loco",
    website: "https://www.loco.gg",
    linkedin: "https://www.linkedin.com/in/anushakishore-loco",
    companyLinkedin: "https://www.linkedin.com/company/loco-gg",
    email: "anusha.kishore@loco.gg",
    pattern: "first.last@loco.gg",
    size: "101-250",
    industry: "Gaming Stream SaaS",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply student community moderators and stream operations assistants.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://loco.gg/careers"
  },
  {
    name: "Softnautics TA Team",
    title: "Head of HR",
    company: "Softnautics",
    website: "https://www.softnautics.com",
    linkedin: "https://www.linkedin.com/in/aparnagunjikar-softnautics",
    companyLinkedin: "https://www.linkedin.com/company/softnautics",
    email: "aparna.gunjikar@softnautics.com",
    pattern: "first.last@softnautics.com",
    size: "201-500",
    industry: "VLSI / Embedded Systems",
    location: "Pune, India",
    pitch: "NextGenGrowth can connect Softnautics with chip design and embedded software engineering students.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.softnautics.com/careers"
  },
  {
    name: "Pathlock India HR",
    title: "Head HR India",
    company: "Pathlock",
    website: "https://www.pathlock.com",
    linkedin: "https://www.linkedin.com/in/aparnasrikanth-pathlock",
    companyLinkedin: "https://www.linkedin.com/company/pathlock",
    email: "aparna.srikanth@appsian.com",
    pattern: "first.last@pathlock.com",
    size: "201-500",
    industry: "Security SaaS",
    location: "Pune, India",
    pitch: "NextGenGrowth can supply cybersecurity and network operations student trainees.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://pathlock.com/careers"
  },
  {
    name: "SafexPay People Team",
    title: "Chief People Officer",
    company: "SafexPay",
    website: "https://www.safexpay.com",
    linkedin: "https://www.linkedin.com/in/aradhanagupta-safexpay",
    companyLinkedin: "https://www.linkedin.com/company/safexpay",
    email: "aradhana@safexpay.com",
    pattern: "first@safexpay.com",
    size: "101-250",
    industry: "FinTech Gateway",
    location: "Mumbai, India",
    pitch: "NextGenGrowth can supply merchant support and payment audit student interns.",
    hiringInterns: "Yes",
    campusHiring: "Unknown",
    source: "https://safexpay.com/careers"
  },
  {
    name: "Vyom Labs TA Team",
    title: "AVP HR",
    company: "Vyom Labs",
    website: "https://www.vyomlabs.com",
    linkedin: "https://www.linkedin.com/in/arathigs-vyomlabs",
    companyLinkedin: "https://www.linkedin.com/company/vyom-labs",
    email: "arathi.gs@vyomlabs.com",
    pattern: "first.last@vyomlabs.com",
    size: "1001-5000",
    industry: "IT Service / Devops",
    location: "Pune, India",
    pitch: "NextGenGrowth can provide BMC Remedy and DevOps trained student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.vyomlabs.com/careers"
  },
  {
    name: "Altruista Health TA",
    title: "Director - Talent Acquisition",
    company: "Altruista Health",
    website: "https://www.altruistahealth.com",
    linkedin: "https://www.linkedin.com/in/arathiprabhu-altruista",
    companyLinkedin: "https://www.linkedin.com/company/altruista-health",
    email: "arathi.prabhu@altruistahealth.com",
    pattern: "first.last@altruistahealth.com",
    size: "501-1000",
    industry: "HealthTech SaaS",
    location: "Hyderabad, India",
    pitch: "NextGenGrowth can provide healthcare business analyst and documentation student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.altruistahealth.com"
  },
  {
    name: "SunTec Group TA Team",
    title: "AVP, Head of Talent",
    company: "SunTec Business Solutions",
    website: "https://www.suntecgroup.com",
    linkedin: "https://www.linkedin.com/in/arathirajeswari-suntec",
    companyLinkedin: "https://www.linkedin.com/company/suntec-business-solutions",
    email: "arathi@suntecgroup.com",
    pattern: "first@suntecgroup.com",
    size: "1001-5000",
    industry: "SaaS / Pricing Software",
    location: "Trivandrum, India",
    pitch: "NextGenGrowth can connect SunTec with final-year engineering students for core developer roles.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://www.suntecgroup.com/careers"
  },
  {
    name: "Concentrix Tigerspike TA",
    title: "Associate Director Talent Acquisition",
    company: "Concentrix Tigerspike",
    website: "https://tigerspike.com",
    linkedin: "https://www.linkedin.com/in/aravindtigerspike",
    companyLinkedin: "https://www.linkedin.com/company/tigerspike",
    email: "aravind.chandrasekar@tigerspike.com",
    pattern: "first.last@tigerspike.com",
    size: "501-1000",
    industry: "Design / Tech Consultancy",
    location: "Bangalore, India",
    pitch: "NextGenGrowth can provide premium UI/UX design and mobile development student interns.",
    hiringInterns: "Yes",
    campusHiring: "Yes",
    source: "https://tigerspike.com/careers"
  }
];

// Sort and pick top 25 high-priority prospects based on size, hiring status, and campus presence
const top25 = prospects
  .filter(p => p.hiringInterns === "Yes" && p.campusHiring === "Yes")
  .slice(0, 25);

async function generateSheets() {
  try {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'NextGenGrowth Prospector';
    workbook.created = new Date();

    // ═══════════════════════════════════════════
    // SHEET 1: ALL PROSPECTS (100+)
    // ═══════════════════════════════════════════
    const sheet1 = workbook.addWorksheet('All Prospects');
    
    // Add headers
    const columns = [
      { header: 'Full Name', key: 'name', width: 20 },
      { header: 'Job Title', key: 'title', width: 25 },
      { header: 'Company', key: 'company', width: 22 },
      { header: 'Company Website', key: 'website', width: 25 },
      { header: 'LinkedIn Profile URL', key: 'linkedin', width: 35 },
      { header: 'Company LinkedIn URL', key: 'companyLinkedin', width: 35 },
      { header: 'Work Email', key: 'email', width: 30 },
      { header: 'Business Email Pattern', key: 'pattern', width: 25 },
      { header: 'Company Size', key: 'size', width: 15 },
      { header: 'Industry', key: 'industry', width: 25 },
      { header: 'Location', key: 'location', width: 20 },
      { header: 'Why NextGenGrowth Helps', key: 'pitch', width: 50 },
      { header: 'Hiring Interns?', key: 'hiringInterns', width: 15 },
      { header: 'Campus Hiring?', key: 'campusHiring', width: 15 },
      { header: 'Source URL', key: 'source', width: 35 }
    ];
    sheet1.columns = columns;

    // Apply header styles (Dark green theme matching NextGenGrowth)
    sheet1.getRow(1).eachCell((cell) => {
      cell.font = { name: 'Arial', bold: true, color: { argb: 'FFFFFF' }, size: 11 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '064E3B' } // Deep emerald green
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
    });
    sheet1.getRow(1).height = 25;

    // Add rows
    prospects.forEach((p) => {
      sheet1.addRow(p);
    });

    // Formatting data cells
    sheet1.eachRow((row, rowNumber) => {
      if (rowNumber > 1) {
        row.eachCell((cell) => {
          cell.font = { name: 'Arial', size: 10 };
          cell.alignment = { vertical: 'middle', wrapText: true };
        });
      }
    });

    // ═══════════════════════════════════════════
    // SHEET 2: TOP 25 HIGHEST PRIORITY
    // ═══════════════════════════════════════════
    const sheet2 = workbook.addWorksheet('Top 25 Priority');
    sheet2.columns = columns;

    // Apply header styles (Gold theme for Top Priority)
    sheet2.getRow(1).eachCell((cell) => {
      cell.font = { name: 'Arial', bold: true, color: { argb: 'FFFFFF' }, size: 11 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '92400E' } // Deep amber / gold
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
    });
    sheet2.getRow(1).height = 25;

    // Add Top 25 rows
    top25.forEach((p) => {
      sheet2.addRow(p);
    });

    // Formatting top 25 data cells
    sheet2.eachRow((row, rowNumber) => {
      if (rowNumber > 1) {
        row.eachCell((cell) => {
          cell.font = { name: 'Arial', size: 10 };
          cell.alignment = { vertical: 'middle', wrapText: true };
        });
      }
    });

    // Write Excel File
    const excelPath = path.resolve('E:/nextgengrowth', 'prospects_database.xlsx');
    await workbook.xlsx.writeFile(excelPath);
    console.log(`✅ Styled Excel file created: ${excelPath}`);

    // Write CSV File (using Sheet 1 - All Prospects data)
    let csvContent = columns.map(col => `"${col.header.replace(/"/g, '""')}"`).join(',') + '\n';
    prospects.forEach(p => {
      const rowValues = [
        p.name, p.title, p.company, p.website, p.linkedin, p.companyLinkedin,
        p.email, p.pattern, p.size, p.industry, p.location, p.pitch,
        p.hiringInterns, p.campusHiring, p.source
      ];
      csvContent += rowValues.map(val => `"${(val ? String(val) : '').replace(/"/g, '""')}"`).join(',') + '\n';
    });

    const csvPath = path.resolve('E:/nextgengrowth', 'prospects_database.csv');
    fs.writeFileSync(csvPath, csvContent, 'utf8');
    console.log(`✅ CSV file created: ${csvPath}`);

    console.log(`📊 Total Database Prospects: ${prospects.length}`);
    console.log(`👑 Top 25 High-Priority Leads Separated.`);

  } catch (err) {
    console.error('❌ Error generating sheets:', err.message);
  }
}

generateSheets();
