module.exports = {
  User: require("./User"),
  OTP: require("./OTP"),
  Application: require("./Application"),
  Earning: require("./Earning"),
  Job: require("./Job"),
  Payment: require("./Payment"),
  ProjectWorkspace: require("./ProjectWorkspace"),
  LongTermRole: require("./LongTermRole"),
  LongTermApplication: require("./LongTermApplication"),
  BlogPost: require("./BlogPost"),
  NewsletterSubscriber: require("./NewsletterSubscriber"),
  MentorRequest: require("./MentorRequest"),
  BlogEvent: require("./BlogEvent"),
  PlatformSetting: require("./PlatformSetting"),
  CampusInquiry: require("./CampusInquiry"),
  CampusApplication: require("./CampusApplication"),
  Coupon: require("./Coupon"),
  Store: require("./Store"),
  Campus: { Inquiry: require("./CampusInquiry"), Application: require("./CampusApplication") },
  Contract: require("./Contract"),
  Proposal: require("./Proposal"),
  PayoutRequest: require("./PayoutRequest"),
};
